import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { IEditorContribution } from 'vs/editor/common/editorCommon';
import { CodeLensModel } from 'vs/editor/contrib/codelens/browser/codelens';
import { ICodeLensCache } from 'vs/editor/contrib/codelens/browser/codeLensCache';
import { ICommandService } from 'vs/platform/commands/common/commands';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { ILanguageFeatureDebounceService } from 'vs/editor/common/services/languageFeatureDebounce';
import { ILanguageFeaturesService } from 'vs/editor/common/services/languageFeatures';
export declare class CodeLensContribution implements IEditorContribution {
    private readonly _editor;
    private readonly _languageFeaturesService;
    private readonly _commandService;
    private readonly _notificationService;
    private readonly _codeLensCache;
    static readonly ID: string;
    private readonly _disposables;
    private readonly _localToDispose;
    private readonly _styleElement;
    private readonly _styleClassName;
    private readonly _lenses;
    private readonly _provideCodeLensDebounce;
    private readonly _resolveCodeLensesDebounce;
    private readonly _resolveCodeLensesScheduler;
    private _getCodeLensModelPromise;
    private _oldCodeLensModels;
    private _currentCodeLensModel;
    private _resolveCodeLensesPromise;
    constructor(_editor: ICodeEditor, _languageFeaturesService: ILanguageFeaturesService, debounceService: ILanguageFeatureDebounceService, _commandService: ICommandService, _notificationService: INotificationService, _codeLensCache: ICodeLensCache);
    dispose(): void;
    private _getLayoutInfo;
    private _updateLensStyle;
    private _localDispose;
    private _onModelChange;
    private _disposeAllLenses;
    private _renderCodeLensSymbols;
    private _resolveCodeLensesInViewportSoon;
    private _resolveCodeLensesInViewport;
    getModel(): CodeLensModel | undefined;
}
