import { URI } from 'vs/base/common/uri';
import { Event, Emitter } from 'vs/base/common/event';
import { Disposable } from 'vs/base/common/lifecycle';
import { IFileService } from 'vs/platform/files/common/files';
import { ConfigurationModel } from 'vs/platform/configuration/common/configurationModels';
import { IConfigurationCache } from 'vs/workbench/services/configuration/common/configuration';
import { IStoredWorkspaceFolder } from 'vs/platform/workspaces/common/workspaces';
import { WorkbenchState, IWorkspaceFolder, IWorkspaceIdentifier } from 'vs/platform/workspace/common/workspace';
import { ConfigurationScope } from 'vs/platform/configuration/common/configurationRegistry';
import { IRemoteAgentService } from 'vs/workbench/services/remote/common/remoteAgentService';
import { IUriIdentityService } from 'vs/platform/uriIdentity/common/uriIdentity';
import { ILogService } from 'vs/platform/log/common/log';
import { IStringDictionary } from 'vs/base/common/collections';
import { IBrowserWorkbenchEnvironmentService } from 'vs/workbench/services/environment/browser/environmentService';
import { DefaultConfiguration as BaseDefaultConfiguration } from 'vs/platform/configuration/common/configurations';
import { IJSONEditingService } from 'vs/workbench/services/configuration/common/jsonEditing';
export declare class DefaultConfiguration extends BaseDefaultConfiguration {
    private readonly configurationCache;
    static readonly DEFAULT_OVERRIDES_CACHE_EXISTS_KEY = "DefaultOverridesCacheExists";
    private readonly configurationRegistry;
    private cachedConfigurationDefaultsOverrides;
    private readonly cacheKey;
    private updateCache;
    constructor(configurationCache: IConfigurationCache, environmentService: IBrowserWorkbenchEnvironmentService);
    protected getConfigurationDefaultOverrides(): IStringDictionary<any>;
    initialize(): Promise<ConfigurationModel>;
    reload(): ConfigurationModel;
    private initiaizeCachedConfigurationDefaultsOverridesPromise;
    private initializeCachedConfigurationDefaultsOverrides;
    protected onDidUpdateConfiguration(properties: string[], defaultsOverrides?: boolean): void;
    private updateCachedConfigurationDefaultsOverrides;
}
export declare class UserConfiguration extends Disposable {
    private settingsResource;
    private tasksResource;
    private readonly fileService;
    private readonly uriIdentityService;
    private readonly logService;
    private readonly _onDidChangeConfiguration;
    readonly onDidChangeConfiguration: Event<ConfigurationModel>;
    private readonly userConfiguration;
    private readonly userConfigurationChangeDisposable;
    private readonly reloadConfigurationScheduler;
    private configurationParseOptions;
    get hasTasksLoaded(): boolean;
    constructor(settingsResource: URI, tasksResource: URI | undefined, scopes: ConfigurationScope[] | undefined, fileService: IFileService, uriIdentityService: IUriIdentityService, logService: ILogService);
    reset(settingsResource: URI, tasksResource: URI | undefined, scopes: ConfigurationScope[] | undefined): Promise<ConfigurationModel>;
    initialize(): Promise<ConfigurationModel>;
    reload(): Promise<ConfigurationModel>;
    reparse(): ConfigurationModel;
    getRestrictedSettings(): string[];
}
export declare class RemoteUserConfiguration extends Disposable {
    private readonly _cachedConfiguration;
    private readonly _fileService;
    private _userConfiguration;
    private _userConfigurationInitializationPromise;
    private readonly _onDidChangeConfiguration;
    readonly onDidChangeConfiguration: Event<ConfigurationModel>;
    private readonly _onDidInitialize;
    readonly onDidInitialize: Event<ConfigurationModel>;
    constructor(remoteAuthority: string, configurationCache: IConfigurationCache, fileService: IFileService, uriIdentityService: IUriIdentityService, remoteAgentService: IRemoteAgentService);
    initialize(): Promise<ConfigurationModel>;
    reload(): Promise<ConfigurationModel>;
    reparse(): ConfigurationModel;
    getRestrictedSettings(): string[];
    private onDidUserConfigurationChange;
    private updateCache;
}
export declare class WorkspaceConfiguration extends Disposable {
    private readonly configurationCache;
    private readonly fileService;
    private readonly uriIdentityService;
    private readonly logService;
    private readonly _cachedConfiguration;
    private _workspaceConfiguration;
    private _workspaceConfigurationDisposables;
    private _workspaceIdentifier;
    private _isWorkspaceTrusted;
    private readonly _onDidUpdateConfiguration;
    readonly onDidUpdateConfiguration: Event<boolean>;
    private _initialized;
    get initialized(): boolean;
    constructor(configurationCache: IConfigurationCache, fileService: IFileService, uriIdentityService: IUriIdentityService, logService: ILogService);
    initialize(workspaceIdentifier: IWorkspaceIdentifier, workspaceTrusted: boolean): Promise<void>;
    reload(): Promise<void>;
    getFolders(): IStoredWorkspaceFolder[];
    setFolders(folders: IStoredWorkspaceFolder[], jsonEditingService: IJSONEditingService): Promise<void>;
    isTransient(): boolean;
    getConfiguration(): ConfigurationModel;
    updateWorkspaceTrust(trusted: boolean): ConfigurationModel;
    reparseWorkspaceSettings(): ConfigurationModel;
    getRestrictedSettings(): string[];
    private waitAndInitialize;
    private doInitialize;
    private isUntrusted;
    private onDidWorkspaceConfigurationChange;
    private updateCache;
}
export declare class FolderConfiguration extends Disposable {
    readonly workspaceFolder: IWorkspaceFolder;
    private readonly workbenchState;
    private workspaceTrusted;
    private readonly configurationCache;
    protected readonly _onDidChange: Emitter<void>;
    readonly onDidChange: Event<void>;
    private folderConfiguration;
    private readonly scopes;
    private readonly configurationFolder;
    private cachedFolderConfiguration;
    constructor(useCache: boolean, workspaceFolder: IWorkspaceFolder, configFolderRelativePath: string, workbenchState: WorkbenchState, workspaceTrusted: boolean, fileService: IFileService, uriIdentityService: IUriIdentityService, logService: ILogService, configurationCache: IConfigurationCache);
    loadConfiguration(): Promise<ConfigurationModel>;
    updateWorkspaceTrust(trusted: boolean): ConfigurationModel;
    reparse(): ConfigurationModel;
    getRestrictedSettings(): string[];
    private isUntrusted;
    private onDidFolderConfigurationChange;
    private createFileServiceBasedConfiguration;
    private updateCache;
}
