import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IResourceEditorInput, IEditorOptions, IResourceEditorInputIdentifier, ITextResourceEditorInput } from 'vs/platform/editor/common/editor';
import { IEditorPane, GroupIdentifier, IUntitledTextResourceEditorInput, IResourceDiffEditorInput, EditorInputWithOptions, IEditorIdentifier, IEditorCloseEvent, ITextDiffEditorPane, IRevertOptions, EditorsOrder, IVisibleEditorPane, IUntypedEditorInput, IFindEditorOptions } from 'vs/workbench/common/editor';
import { EditorInput } from 'vs/workbench/common/editor/editorInput';
import { IFileService } from 'vs/platform/files/common/files';
import { Event } from 'vs/base/common/event';
import { URI } from 'vs/base/common/uri';
import { IEditorGroupsService, IEditorGroup, IEditorReplacement, ICloseEditorOptions } from 'vs/workbench/services/editor/common/editorGroupsService';
import { IUntypedEditorReplacement, ISaveEditorsOptions, ISaveAllEditorsOptions, IRevertAllEditorsOptions, IOpenEditorsOptions, PreferredGroup, IEditorsChangeEvent } from 'vs/workbench/services/editor/common/editorService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { Disposable } from 'vs/base/common/lifecycle';
import { ICodeEditor, IDiffEditor } from 'vs/editor/browser/editorBrowser';
import { EditorServiceImpl } from 'vs/workbench/browser/parts/editor/editor';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { IUriIdentityService } from 'vs/platform/uriIdentity/common/uriIdentity';
import { IEditorResolverService } from 'vs/workbench/services/editor/common/editorResolverService';
import { IWorkingCopyService } from 'vs/workbench/services/workingCopy/common/workingCopyService';
import { IWorkspaceTrustRequestService } from 'vs/platform/workspace/common/workspaceTrust';
import { IHostService } from 'vs/workbench/services/host/browser/host';
import { ITextEditorService } from 'vs/workbench/services/textfile/common/textEditorService';
export declare class EditorService extends Disposable implements EditorServiceImpl {
    private readonly editorGroupService;
    private readonly instantiationService;
    private readonly fileService;
    private readonly configurationService;
    private readonly contextService;
    private readonly uriIdentityService;
    private readonly editorResolverService;
    private readonly workingCopyService;
    private readonly workspaceTrustRequestService;
    private readonly hostService;
    private readonly textEditorService;
    readonly _serviceBrand: undefined;
    private readonly _onDidActiveEditorChange;
    readonly onDidActiveEditorChange: Event<void>;
    private readonly _onDidVisibleEditorsChange;
    readonly onDidVisibleEditorsChange: Event<void>;
    private readonly _onDidEditorsChange;
    readonly onDidEditorsChange: Event<IEditorsChangeEvent>;
    private readonly _onDidCloseEditor;
    readonly onDidCloseEditor: Event<IEditorCloseEvent>;
    private readonly _onDidOpenEditorFail;
    readonly onDidOpenEditorFail: Event<IEditorIdentifier>;
    private readonly _onDidMostRecentlyActiveEditorsChange;
    readonly onDidMostRecentlyActiveEditorsChange: Event<void>;
    constructor(editorGroupService: IEditorGroupsService, instantiationService: IInstantiationService, fileService: IFileService, configurationService: IConfigurationService, contextService: IWorkspaceContextService, uriIdentityService: IUriIdentityService, editorResolverService: IEditorResolverService, workingCopyService: IWorkingCopyService, workspaceTrustRequestService: IWorkspaceTrustRequestService, hostService: IHostService, textEditorService: ITextEditorService);
    private registerListeners;
    private lastActiveEditor;
    private onEditorGroupsReady;
    private handleActiveEditorChange;
    private doHandleActiveEditorChangeEvent;
    private registerGroupListeners;
    private readonly activeOutOfWorkspaceWatchers;
    private handleVisibleEditorsChange;
    private onDidRunFileOperation;
    private onDidFilesChange;
    private handleMovedFile;
    private closeOnFileDelete;
    private onConfigurationUpdated;
    private handleDeletedFile;
    private getAllNonDirtyEditors;
    private readonly editorsObserver;
    get activeEditorPane(): IVisibleEditorPane | undefined;
    get activeTextEditorControl(): ICodeEditor | IDiffEditor | undefined;
    get activeTextEditorLanguageId(): string | undefined;
    get count(): number;
    get editors(): EditorInput[];
    getEditors(order: EditorsOrder, options?: {
        excludeSticky?: boolean;
    }): readonly IEditorIdentifier[];
    get activeEditor(): EditorInput | undefined;
    get visibleEditorPanes(): IVisibleEditorPane[];
    get visibleTextEditorControls(): Array<ICodeEditor | IDiffEditor>;
    get visibleEditors(): EditorInput[];
    openEditor(editor: EditorInput, options?: IEditorOptions, group?: PreferredGroup): Promise<IEditorPane | undefined>;
    openEditor(editor: IUntypedEditorInput, group?: PreferredGroup): Promise<IEditorPane | undefined>;
    openEditor(editor: IResourceEditorInput, group?: PreferredGroup): Promise<IEditorPane | undefined>;
    openEditor(editor: ITextResourceEditorInput | IUntitledTextResourceEditorInput, group?: PreferredGroup): Promise<IEditorPane | undefined>;
    openEditor(editor: IResourceDiffEditorInput, group?: PreferredGroup): Promise<ITextDiffEditorPane | undefined>;
    openEditor(editor: EditorInput | IUntypedEditorInput, optionsOrPreferredGroup?: IEditorOptions | PreferredGroup, preferredGroup?: PreferredGroup): Promise<IEditorPane | undefined>;
    openEditors(editors: EditorInputWithOptions[], group?: PreferredGroup, options?: IOpenEditorsOptions): Promise<IEditorPane[]>;
    openEditors(editors: IUntypedEditorInput[], group?: PreferredGroup, options?: IOpenEditorsOptions): Promise<IEditorPane[]>;
    openEditors(editors: Array<EditorInputWithOptions | IUntypedEditorInput>, group?: PreferredGroup, options?: IOpenEditorsOptions): Promise<IEditorPane[]>;
    private handleWorkspaceTrust;
    private extractEditorResources;
    isOpened(editor: IResourceEditorInputIdentifier): boolean;
    isVisible(editor: EditorInput): boolean;
    closeEditor({ editor, groupId }: IEditorIdentifier, options?: ICloseEditorOptions): Promise<void>;
    closeEditors(editors: IEditorIdentifier[], options?: ICloseEditorOptions): Promise<void>;
    findEditors(resource: URI, options?: IFindEditorOptions): readonly IEditorIdentifier[];
    findEditors(editor: IResourceEditorInputIdentifier, options?: IFindEditorOptions): readonly IEditorIdentifier[];
    findEditors(resource: URI, options: IFindEditorOptions | undefined, group: IEditorGroup | GroupIdentifier): readonly EditorInput[];
    findEditors(editor: IResourceEditorInputIdentifier, options: IFindEditorOptions | undefined, group: IEditorGroup | GroupIdentifier): EditorInput | undefined;
    findEditors(arg1: URI | IResourceEditorInputIdentifier, options: IFindEditorOptions | undefined, arg2?: IEditorGroup | GroupIdentifier): readonly IEditorIdentifier[] | readonly EditorInput[] | EditorInput | undefined;
    replaceEditors(replacements: IUntypedEditorReplacement[], group: IEditorGroup | GroupIdentifier): Promise<void>;
    replaceEditors(replacements: IEditorReplacement[], group: IEditorGroup | GroupIdentifier): Promise<void>;
    save(editors: IEditorIdentifier | IEditorIdentifier[], options?: ISaveEditorsOptions): Promise<boolean>;
    saveAll(options?: ISaveAllEditorsOptions): Promise<boolean>;
    revert(editors: IEditorIdentifier | IEditorIdentifier[], options?: IRevertOptions): Promise<boolean>;
    revertAll(options?: IRevertAllEditorsOptions): Promise<boolean>;
    private getAllDirtyEditors;
    private getUniqueEditors;
    dispose(): void;
}
