import 'vs/css!./media/notificationsToasts';
import { INotificationsModel } from 'vs/workbench/common/notifications';
import { Dimension } from 'vs/base/browser/dom';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { Event } from 'vs/base/common/event';
import { IWorkbenchLayoutService } from 'vs/workbench/services/layout/browser/layoutService';
import { IThemeService, Themable } from 'vs/platform/theme/common/themeService';
import { IEditorGroupsService } from 'vs/workbench/services/editor/common/editorGroupsService';
import { INotificationsToastController } from 'vs/workbench/browser/parts/notifications/notificationsCommands';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { ILifecycleService } from 'vs/workbench/services/lifecycle/common/lifecycle';
import { IHostService } from 'vs/workbench/services/host/browser/host';
export declare class NotificationsToasts extends Themable implements INotificationsToastController {
    private readonly container;
    private readonly model;
    private readonly instantiationService;
    private readonly layoutService;
    private readonly editorGroupService;
    private readonly contextKeyService;
    private readonly lifecycleService;
    private readonly hostService;
    private static readonly MAX_WIDTH;
    private static readonly MAX_NOTIFICATIONS;
    private static readonly PURGE_TIMEOUT;
    private static readonly SPAM_PROTECTION;
    private readonly _onDidChangeVisibility;
    readonly onDidChangeVisibility: Event<void>;
    private _isVisible;
    get isVisible(): boolean;
    private notificationsToastsContainer;
    private workbenchDimensions;
    private isNotificationsCenterVisible;
    private readonly mapNotificationToToast;
    private readonly mapNotificationToDisposable;
    private readonly notificationsToastsVisibleContextKey;
    private readonly addedToastsIntervalCounter;
    constructor(container: HTMLElement, model: INotificationsModel, instantiationService: IInstantiationService, layoutService: IWorkbenchLayoutService, themeService: IThemeService, editorGroupService: IEditorGroupsService, contextKeyService: IContextKeyService, lifecycleService: ILifecycleService, hostService: IHostService);
    private registerListeners;
    private onDidChangeNotification;
    private addToast;
    private doAddToast;
    private purgeNotification;
    private removeToast;
    private removeToasts;
    private doHide;
    hide(): void;
    focus(): boolean;
    focusNext(): boolean;
    focusPrevious(): boolean;
    focusFirst(): boolean;
    focusLast(): boolean;
    update(isCenterVisible: boolean): void;
    protected updateStyles(): void;
    private getToasts;
    layout(dimension: Dimension | undefined): void;
    private computeMaxDimensions;
    private layoutLists;
    private layoutContainer;
    private updateToastVisibility;
    private isToastInDOM;
}
