import { RawContextKey } from 'vs/platform/contextkey/common/contextkey';
export declare const FindInFilesActionId = "workbench.action.findInFiles";
export declare const FocusActiveEditorCommandId = "search.action.focusActiveEditor";
export declare const FocusSearchFromResults = "search.action.focusSearchFromResults";
export declare const OpenMatch = "search.action.openResult";
export declare const OpenMatchToSide = "search.action.openResultToSide";
export declare const RemoveActionId = "search.action.remove";
export declare const CopyPathCommandId = "search.action.copyPath";
export declare const CopyMatchCommandId = "search.action.copyMatch";
export declare const CopyAllCommandId = "search.action.copyAll";
export declare const OpenInEditorCommandId = "search.action.openInEditor";
export declare const ClearSearchHistoryCommandId = "search.action.clearHistory";
export declare const FocusSearchListCommandID = "search.action.focusSearchList";
export declare const ReplaceActionId = "search.action.replace";
export declare const ReplaceAllInFileActionId = "search.action.replaceAllInFile";
export declare const ReplaceAllInFolderActionId = "search.action.replaceAllInFolder";
export declare const CloseReplaceWidgetActionId = "closeReplaceInFilesWidget";
export declare const ToggleCaseSensitiveCommandId = "toggleSearchCaseSensitive";
export declare const ToggleWholeWordCommandId = "toggleSearchWholeWord";
export declare const ToggleRegexCommandId = "toggleSearchRegex";
export declare const TogglePreserveCaseId = "toggleSearchPreserveCase";
export declare const AddCursorsAtSearchResults = "addCursorsAtSearchResults";
export declare const RevealInSideBarForSearchResults = "search.action.revealInSideBar";
export declare const ReplaceInFilesActionId = "workbench.action.replaceInFiles";
export declare const ShowAllSymbolsActionId = "workbench.action.showAllSymbols";
export declare const CancelSearchActionId = "search.action.cancel";
export declare const RefreshSearchResultsActionId = "search.action.refreshSearchResults";
export declare const FocusNextSearchResultActionId = "search.action.focusNextSearchResult";
export declare const FocusPreviousSearchResultActionId = "search.action.focusPreviousSearchResult";
export declare const ToggleSearchOnTypeActionId = "workbench.action.toggleSearchOnType";
export declare const CollapseSearchResultsActionId = "search.action.collapseSearchResults";
export declare const ExpandSearchResultsActionId = "search.action.expandSearchResults";
export declare const ClearSearchResultsActionId = "search.action.clearSearchResults";
export declare const ViewAsTreeActionId = "search.action.viewAsTree";
export declare const ViewAsListActionId = "search.action.viewAsList";
export declare const ToggleQueryDetailsActionId = "workbench.action.search.toggleQueryDetails";
export declare const ExcludeFolderFromSearchId = "search.action.excludeFromSearch";
export declare const FocusNextInputActionId = "search.focus.nextInputBox";
export declare const FocusPreviousInputActionId = "search.focus.previousInputBox";
export declare const RestrictSearchToFolderId = "search.action.restrictSearchToFolder";
export declare const FindInFolderId = "filesExplorer.findInFolder";
export declare const FindInWorkspaceId = "filesExplorer.findInWorkspace";
export declare const SearchViewVisibleKey: RawContextKey<boolean>;
export declare const SearchViewFocusedKey: RawContextKey<boolean>;
export declare const InputBoxFocusedKey: RawContextKey<boolean>;
export declare const SearchInputBoxFocusedKey: RawContextKey<boolean>;
export declare const ReplaceInputBoxFocusedKey: RawContextKey<boolean>;
export declare const PatternIncludesFocusedKey: RawContextKey<boolean>;
export declare const PatternExcludesFocusedKey: RawContextKey<boolean>;
export declare const ReplaceActiveKey: RawContextKey<boolean>;
export declare const HasSearchResults: RawContextKey<boolean>;
export declare const FirstMatchFocusKey: RawContextKey<boolean>;
export declare const FileMatchOrMatchFocusKey: RawContextKey<boolean>;
export declare const FileMatchOrFolderMatchFocusKey: RawContextKey<boolean>;
export declare const FileMatchOrFolderMatchWithResourceFocusKey: RawContextKey<boolean>;
export declare const FileFocusKey: RawContextKey<boolean>;
export declare const FolderFocusKey: RawContextKey<boolean>;
export declare const ResourceFolderFocusKey: RawContextKey<boolean>;
export declare const MatchFocusKey: RawContextKey<boolean>;
export declare const ViewHasSearchPatternKey: RawContextKey<boolean>;
export declare const ViewHasReplacePatternKey: RawContextKey<boolean>;
export declare const ViewHasFilePatternKey: RawContextKey<boolean>;
export declare const ViewHasSomeCollapsibleKey: RawContextKey<boolean>;
export declare const InTreeViewKey: RawContextKey<boolean>;
