import { Event } from 'vs/base/common/event';
import { Disposable, IDisposable } from 'vs/base/common/lifecycle';
import { URI } from 'vs/base/common/uri';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IFileService } from 'vs/platform/files/common/files';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IUriIdentityService } from 'vs/platform/uriIdentity/common/uriIdentity';
import { CustomEditorCapabilities, CustomEditorInfo, CustomEditorInfoCollection, ICustomEditorService } from 'vs/workbench/contrib/customEditor/common/customEditor';
import { CustomEditorModelManager } from 'vs/workbench/contrib/customEditor/common/customEditorModelManager';
import { IEditorGroupsService } from 'vs/workbench/services/editor/common/editorGroupsService';
import { IEditorResolverService, IEditorType } from 'vs/workbench/services/editor/common/editorResolverService';
import { IEditorService } from 'vs/workbench/services/editor/common/editorService';
export declare class CustomEditorService extends Disposable implements ICustomEditorService {
    private readonly editorService;
    private readonly editorGroupService;
    private readonly instantiationService;
    private readonly uriIdentityService;
    private readonly editorResolverService;
    _serviceBrand: any;
    private readonly _contributedEditors;
    private _untitledCounter;
    private readonly _editorResolverDisposables;
    private readonly _editorCapabilities;
    private readonly _models;
    private readonly _activeCustomEditorId;
    private readonly _focusedCustomEditorIsEditable;
    private readonly _onDidChangeEditorTypes;
    readonly onDidChangeEditorTypes: Event<void>;
    private readonly _fileEditorFactory;
    constructor(contextKeyService: IContextKeyService, fileService: IFileService, storageService: IStorageService, editorService: IEditorService, editorGroupService: IEditorGroupsService, instantiationService: IInstantiationService, uriIdentityService: IUriIdentityService, editorResolverService: IEditorResolverService);
    getEditorTypes(): IEditorType[];
    private withActiveCustomEditor;
    private registerContributionPoints;
    private createDiffEditorInput;
    get models(): CustomEditorModelManager;
    getCustomEditor(viewType: string): CustomEditorInfo | undefined;
    getContributedCustomEditors(resource: URI): CustomEditorInfoCollection;
    getUserConfiguredCustomEditors(resource: URI): CustomEditorInfoCollection;
    getAllCustomEditors(resource: URI): CustomEditorInfoCollection;
    registerCustomEditorCapabilities(viewType: string, options: CustomEditorCapabilities): IDisposable;
    getCustomEditorCapabilities(viewType: string): CustomEditorCapabilities | undefined;
    private updateContexts;
    private handleMovedFileInOpenedFileEditors;
}
