import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IExtensionManifest, ExtensionUntrustedWorkspaceSupportType, ExtensionVirtualWorkspaceSupportType, IExtensionIdentifier } from 'vs/platform/extensions/common/extensions';
import { ExtensionKind } from 'vs/platform/environment/common/environment';
import { IProductService } from 'vs/platform/product/common/productService';
import { Disposable } from 'vs/base/common/lifecycle';
import { IWorkspaceTrustEnablementService } from 'vs/platform/workspace/common/workspaceTrust';
import { ILogService } from 'vs/platform/log/common/log';
export declare const IExtensionManifestPropertiesService: import("vs/platform/instantiation/common/instantiation").ServiceIdentifier<IExtensionManifestPropertiesService>;
export interface IExtensionManifestPropertiesService {
    readonly _serviceBrand: undefined;
    prefersExecuteOnUI(manifest: IExtensionManifest): boolean;
    prefersExecuteOnWorkspace(manifest: IExtensionManifest): boolean;
    prefersExecuteOnWeb(manifest: IExtensionManifest): boolean;
    canExecuteOnUI(manifest: IExtensionManifest): boolean;
    canExecuteOnWorkspace(manifest: IExtensionManifest): boolean;
    canExecuteOnWeb(manifest: IExtensionManifest): boolean;
    getExtensionKind(manifest: IExtensionManifest): ExtensionKind[];
    getUserConfiguredExtensionKind(extensionIdentifier: IExtensionIdentifier): ExtensionKind[] | undefined;
    getExtensionUntrustedWorkspaceSupportType(manifest: IExtensionManifest): ExtensionUntrustedWorkspaceSupportType;
    getExtensionVirtualWorkspaceSupportType(manifest: IExtensionManifest): ExtensionVirtualWorkspaceSupportType;
}
export declare class ExtensionManifestPropertiesService extends Disposable implements IExtensionManifestPropertiesService {
    private readonly productService;
    private readonly configurationService;
    private readonly workspaceTrustEnablementService;
    private readonly logService;
    readonly _serviceBrand: undefined;
    private _extensionPointExtensionKindsMap;
    private _productExtensionKindsMap;
    private _configuredExtensionKindsMap;
    private _productVirtualWorkspaceSupportMap;
    private _configuredVirtualWorkspaceSupportMap;
    private readonly _configuredExtensionWorkspaceTrustRequestMap;
    private readonly _productExtensionWorkspaceTrustRequestMap;
    constructor(productService: IProductService, configurationService: IConfigurationService, workspaceTrustEnablementService: IWorkspaceTrustEnablementService, logService: ILogService);
    prefersExecuteOnUI(manifest: IExtensionManifest): boolean;
    prefersExecuteOnWorkspace(manifest: IExtensionManifest): boolean;
    prefersExecuteOnWeb(manifest: IExtensionManifest): boolean;
    canExecuteOnUI(manifest: IExtensionManifest): boolean;
    canExecuteOnWorkspace(manifest: IExtensionManifest): boolean;
    canExecuteOnWeb(manifest: IExtensionManifest): boolean;
    getExtensionKind(manifest: IExtensionManifest): ExtensionKind[];
    getUserConfiguredExtensionKind(extensionIdentifier: IExtensionIdentifier): ExtensionKind[] | undefined;
    getExtensionUntrustedWorkspaceSupportType(manifest: IExtensionManifest): ExtensionUntrustedWorkspaceSupportType;
    getExtensionVirtualWorkspaceSupportType(manifest: IExtensionManifest): ExtensionVirtualWorkspaceSupportType;
    private deduceExtensionKind;
    private getSupportedExtensionKindsForExtensionPoint;
    private getConfiguredExtensionKind;
    private getProductExtensionKind;
    private getProductVirtualWorkspaceSupport;
    private getConfiguredVirtualWorkspaceSupport;
    private getConfiguredExtensionWorkspaceTrustRequest;
    private getProductExtensionWorkspaceTrustRequest;
    private toArray;
}
