import { CancelablePromise } from 'vs/base/common/async';
import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { ICodeEditorService } from 'vs/editor/browser/services/codeEditorService';
import { Range } from 'vs/editor/common/core/range';
import { IEditorContribution } from 'vs/editor/common/editorCommon';
import { Location } from 'vs/editor/common/languages';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IContextKeyService, RawContextKey } from 'vs/platform/contextkey/common/contextkey';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { OneReference, ReferencesModel } from '../referencesModel';
export declare const ctxReferenceSearchVisible: RawContextKey<boolean>;
export declare abstract class ReferencesController implements IEditorContribution {
    private readonly _defaultTreeKeyboardSupport;
    private readonly _editor;
    private readonly _editorService;
    private readonly _notificationService;
    private readonly _instantiationService;
    private readonly _storageService;
    private readonly _configurationService;
    static readonly ID = "editor.contrib.referencesController";
    private readonly _disposables;
    private _widget?;
    private _model?;
    private _peekMode?;
    private _requestIdPool;
    private _ignoreModelChangeEvent;
    private readonly _referenceSearchVisible;
    static get(editor: ICodeEditor): ReferencesController | null;
    constructor(_defaultTreeKeyboardSupport: boolean, _editor: ICodeEditor, contextKeyService: IContextKeyService, _editorService: ICodeEditorService, _notificationService: INotificationService, _instantiationService: IInstantiationService, _storageService: IStorageService, _configurationService: IConfigurationService);
    dispose(): void;
    toggleWidget(range: Range, modelPromise: CancelablePromise<ReferencesModel>, peekMode: boolean): void;
    changeFocusBetweenPreviewAndReferences(): void;
    goToNextOrPreviousReference(fwd: boolean): Promise<void>;
    revealReference(reference: OneReference): Promise<void>;
    closeWidget(focusEditor?: boolean): void;
    private _gotoReference;
    openReference(ref: Location, sideBySide: boolean, pinned: boolean): void;
}
