import { RawContextKey } from 'vs/platform/contextkey/common/contextkey';
export declare const IsMacContext: RawContextKey<boolean>;
export declare const IsLinuxContext: RawContextKey<boolean>;
export declare const IsWindowsContext: RawContextKey<boolean>;
export declare const IsWebContext: RawContextKey<boolean>;
export declare const IsMacNativeContext: RawContextKey<boolean>;
export declare const IsIOSContext: RawContextKey<boolean>;
export declare const IsMobileContext: RawContextKey<boolean>;
export declare const IsDevelopmentContext: RawContextKey<boolean>;
export declare const ProductQualityContext: RawContextKey<string>;
export declare const InputFocusedContextKey = "inputFocus";
export declare const InputFocusedContext: RawContextKey<boolean>;
