import { Disposable } from 'vs/base/common/lifecycle';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IEditorGroupsService } from 'vs/workbench/services/editor/common/editorGroupsService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IWorkbenchEnvironmentService } from 'vs/workbench/services/environment/common/environmentService';
import { IEditorService } from 'vs/workbench/services/editor/common/editorService';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { IWorkbenchLayoutService } from 'vs/workbench/services/layout/browser/layoutService';
import { IWorkingCopyService } from 'vs/workbench/services/workingCopy/common/workingCopyService';
import { IEditorResolverService } from 'vs/workbench/services/editor/common/editorResolverService';
import { IPaneCompositePartService } from 'vs/workbench/services/panecomposite/browser/panecomposite';
import { IProductService } from 'vs/platform/product/common/productService';
export declare class WorkbenchContextKeysHandler extends Disposable {
    private readonly contextKeyService;
    private readonly contextService;
    private readonly configurationService;
    private readonly environmentService;
    private readonly productService;
    private readonly editorService;
    private readonly editorResolverService;
    private readonly editorGroupService;
    private readonly layoutService;
    private readonly paneCompositeService;
    private readonly workingCopyService;
    private inputFocusedContext;
    private dirtyWorkingCopiesContext;
    private activeEditorContext;
    private activeEditorIsReadonly;
    private activeEditorCanRevert;
    private activeEditorCanSplitInGroup;
    private activeEditorAvailableEditorIds;
    private activeEditorGroupEmpty;
    private activeEditorGroupIndex;
    private activeEditorGroupLast;
    private activeEditorGroupLocked;
    private multipleEditorGroupsContext;
    private editorsVisibleContext;
    private textCompareEditorVisibleContext;
    private textCompareEditorActiveContext;
    private sideBySideEditorActiveContext;
    private splitEditorsVerticallyContext;
    private workbenchStateContext;
    private workspaceFolderCountContext;
    private openFolderWorkspaceSupportContext;
    private enterMultiRootWorkspaceSupportContext;
    private emptyWorkspaceSupportContext;
    private virtualWorkspaceContext;
    private temporaryWorkspaceContext;
    private inZenModeContext;
    private isFullscreenContext;
    private isCenteredLayoutContext;
    private sideBarVisibleContext;
    private editorAreaVisibleContext;
    private panelPositionContext;
    private panelVisibleContext;
    private panelAlignmentContext;
    private panelMaximizedContext;
    private auxiliaryBarVisibleContext;
    private editorTabsVisibleContext;
    constructor(contextKeyService: IContextKeyService, contextService: IWorkspaceContextService, configurationService: IConfigurationService, environmentService: IWorkbenchEnvironmentService, productService: IProductService, editorService: IEditorService, editorResolverService: IEditorResolverService, editorGroupService: IEditorGroupsService, layoutService: IWorkbenchLayoutService, paneCompositeService: IPaneCompositePartService, workingCopyService: IWorkingCopyService);
    private registerListeners;
    private updateEditorAreaContextKeys;
    private updateEditorContextKeys;
    private updateEditorGroupContextKeys;
    private updateInputContextKeys;
    private updateWorkbenchStateContextKey;
    private updateWorkspaceFolderCountContextKey;
    private updateSplitEditorsVerticallyContext;
    private getWorkbenchStateString;
    private updateSideBarContextKeys;
    private updateWorkspaceContextKeys;
}
