import { IRemoteAgentService } from 'vs/workbench/services/remote/common/remoteAgentService';
import { Disposable } from 'vs/base/common/lifecycle';
import { IMenuService } from 'vs/platform/actions/common/actions';
import { IWorkbenchContribution } from 'vs/workbench/common/contributions';
import { IStatusbarService } from 'vs/workbench/services/statusbar/browser/statusbar';
import { ILabelService } from 'vs/platform/label/common/label';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { ICommandService } from 'vs/platform/commands/common/commands';
import { IExtensionService } from 'vs/workbench/services/extensions/common/extensions';
import { IQuickInputService } from 'vs/platform/quickinput/common/quickInput';
import { IBrowserWorkbenchEnvironmentService } from 'vs/workbench/services/environment/browser/environmentService';
import { IRemoteAuthorityResolverService } from 'vs/platform/remote/common/remoteAuthorityResolver';
import { IHostService } from 'vs/workbench/services/host/browser/host';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { ILogService } from 'vs/platform/log/common/log';
import { IExtensionGalleryService } from 'vs/platform/extensionManagement/common/extensionManagement';
export declare class RemoteStatusIndicator extends Disposable implements IWorkbenchContribution {
    private readonly statusbarService;
    private readonly environmentService;
    private readonly labelService;
    private contextKeyService;
    private menuService;
    private readonly quickInputService;
    private readonly commandService;
    private readonly extensionService;
    private readonly remoteAgentService;
    private readonly remoteAuthorityResolverService;
    private readonly hostService;
    private readonly workspaceContextService;
    private readonly logService;
    private readonly extensionGalleryService;
    private static readonly REMOTE_ACTIONS_COMMAND_ID;
    private static readonly CLOSE_REMOTE_COMMAND_ID;
    private static readonly SHOW_CLOSE_REMOTE_COMMAND_ID;
    private static readonly INSTALL_REMOTE_EXTENSIONS_ID;
    private static readonly REMOTE_STATUS_LABEL_MAX_LENGTH;
    private remoteStatusEntry;
    private readonly legacyIndicatorMenu;
    private readonly remoteIndicatorMenu;
    private remoteMenuActionsGroups;
    private readonly remoteAuthority;
    private virtualWorkspaceLocation;
    private connectionState;
    private readonly connectionStateContextKey;
    private loggedInvalidGroupNames;
    constructor(statusbarService: IStatusbarService, environmentService: IBrowserWorkbenchEnvironmentService, labelService: ILabelService, contextKeyService: IContextKeyService, menuService: IMenuService, quickInputService: IQuickInputService, commandService: ICommandService, extensionService: IExtensionService, remoteAgentService: IRemoteAgentService, remoteAuthorityResolverService: IRemoteAuthorityResolverService, hostService: IHostService, workspaceContextService: IWorkspaceContextService, logService: ILogService, extensionGalleryService: IExtensionGalleryService);
    private registerActions;
    private registerListeners;
    private updateVirtualWorkspaceLocation;
    private updateWhenInstalledExtensionsRegistered;
    private setState;
    private validatedGroup;
    private getRemoteMenuActions;
    private updateRemoteStatusIndicator;
    private renderRemoteStatusIndicator;
    private showRemoteMenu;
    private hasRemoteMenuCommands;
}
