import { Disposable } from 'vs/base/common/lifecycle';
import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { Position } from 'vs/editor/common/core/position';
import { IEditorContribution } from 'vs/editor/common/editorCommon';
import { IModelDecoration } from 'vs/editor/common/model';
import { ILanguageFeatureDebounceService } from 'vs/editor/common/services/languageFeatureDebounce';
import { ILanguageFeaturesService } from 'vs/editor/common/services/languageFeatures';
import { IColorData } from 'vs/editor/contrib/colorPicker/browser/color';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
export declare const ColorDecorationInjectedTextMarker: any;
export declare class ColorDetector extends Disposable implements IEditorContribution {
    private readonly _editor;
    private readonly _configurationService;
    private readonly _languageFeaturesService;
    static readonly ID: string;
    static readonly RECOMPUTE_TIME = 1000;
    private readonly _localToDispose;
    private _computePromise;
    private _timeoutTimer;
    private _debounceInformation;
    private _decorationsIds;
    private _colorDatas;
    private readonly _colorDecoratorIds;
    private _isEnabled;
    private readonly _ruleFactory;
    constructor(_editor: ICodeEditor, _configurationService: IConfigurationService, _languageFeaturesService: ILanguageFeaturesService, languageFeatureDebounceService: ILanguageFeatureDebounceService);
    isEnabled(): boolean;
    static get(editor: ICodeEditor): ColorDetector | null;
    dispose(): void;
    private onModelChanged;
    private beginCompute;
    private stop;
    private updateDecorations;
    private _colorDecorationClassRefs;
    private updateColorDecorators;
    private removeAllDecorations;
    getColorData(position: Position): IColorData | null;
    isColorDecoration(decoration: IModelDecoration): boolean;
}
