import { Color } from 'vs/base/common/color';
import * as languages from 'vs/editor/common/languages';
import { IColorTheme } from 'vs/platform/theme/common/themeService';
export declare const commentThreadRangeBackground: string;
export declare const commentThreadRangeBorder: string;
export declare const commentThreadRangeActiveBackground: string;
export declare const commentThreadRangeActiveBorder: string;
export declare const commentThreadStateColorVar = "--comment-thread-state-color";
export declare const commentViewThreadStateColorVar = "--comment-view-thread-state-color";
export declare const commentThreadStateBackgroundColorVar = "--comment-thread-state-background-color";
export declare function getCommentThreadStateColor(state: languages.CommentThreadState | undefined, theme: IColorTheme): Color | undefined;
