import { VSBuffer, VSBufferReadable, VSBufferReadableStream } from 'vs/base/common/buffer';
import { CancellationToken } from 'vs/base/common/cancellation';
import { Disposable, IDisposable } from 'vs/base/common/lifecycle';
import { URI } from 'vs/base/common/uri';
import { FileChangesEvent, IFileDeleteOptions, FileOperationEvent, FileSystemProviderCapabilities, ICreateFileOptions, IFileContent, IFileService, IFileStat, IFileStatWithMetadata, IFileStreamContent, IFileSystemProvider, IFileSystemProviderActivationEvent, IFileSystemProviderCapabilitiesChangeEvent, IFileSystemProviderRegistrationEvent, IReadFileOptions, IReadFileStreamOptions, IResolveFileOptions, IFileStatResult, IFileStatResultWithMetadata, IResolveMetadataFileOptions, IFileStatWithPartialMetadata, IWatchOptions, IWriteFileOptions } from 'vs/platform/files/common/files';
import { ILogService } from 'vs/platform/log/common/log';
export declare class FileService extends Disposable implements IFileService {
    private readonly logService;
    readonly _serviceBrand: undefined;
    private readonly BUFFER_SIZE;
    constructor(logService: ILogService);
    private readonly _onDidChangeFileSystemProviderRegistrations;
    readonly onDidChangeFileSystemProviderRegistrations: import("vs/base/common/event").Event<IFileSystemProviderRegistrationEvent>;
    private readonly _onWillActivateFileSystemProvider;
    readonly onWillActivateFileSystemProvider: import("vs/base/common/event").Event<IFileSystemProviderActivationEvent>;
    private readonly _onDidChangeFileSystemProviderCapabilities;
    readonly onDidChangeFileSystemProviderCapabilities: import("vs/base/common/event").Event<IFileSystemProviderCapabilitiesChangeEvent>;
    private readonly provider;
    registerProvider(scheme: string, provider: IFileSystemProvider): IDisposable;
    getProvider(scheme: string): IFileSystemProvider | undefined;
    activateProvider(scheme: string): Promise<void>;
    canHandleResource(resource: URI): Promise<boolean>;
    hasProvider(resource: URI): boolean;
    hasCapability(resource: URI, capability: FileSystemProviderCapabilities): boolean;
    listCapabilities(): Iterable<{
        scheme: string;
        capabilities: FileSystemProviderCapabilities;
    }>;
    protected withProvider(resource: URI): Promise<IFileSystemProvider>;
    private withReadProvider;
    private withWriteProvider;
    private readonly _onDidRunOperation;
    readonly onDidRunOperation: import("vs/base/common/event").Event<FileOperationEvent>;
    resolve(resource: URI, options: IResolveMetadataFileOptions): Promise<IFileStatWithMetadata>;
    resolve(resource: URI, options?: IResolveFileOptions): Promise<IFileStat>;
    private doResolveFile;
    private toFileStat;
    resolveAll(toResolve: {
        resource: URI;
        options?: IResolveFileOptions;
    }[]): Promise<IFileStatResult[]>;
    resolveAll(toResolve: {
        resource: URI;
        options: IResolveMetadataFileOptions;
    }[]): Promise<IFileStatResultWithMetadata[]>;
    stat(resource: URI): Promise<IFileStatWithPartialMetadata>;
    exists(resource: URI): Promise<boolean>;
    canCreateFile(resource: URI, options?: ICreateFileOptions): Promise<Error | true>;
    private doValidateCreateFile;
    createFile(resource: URI, bufferOrReadableOrStream?: VSBuffer | VSBufferReadable | VSBufferReadableStream, options?: ICreateFileOptions): Promise<IFileStatWithMetadata>;
    writeFile(resource: URI, bufferOrReadableOrStream: VSBuffer | VSBufferReadable | VSBufferReadableStream, options?: IWriteFileOptions): Promise<IFileStatWithMetadata>;
    private validateWriteFile;
    readFile(resource: URI, options?: IReadFileOptions, token?: CancellationToken): Promise<IFileContent>;
    private doReadFileAtomic;
    private doReadFile;
    readFileStream(resource: URI, options?: IReadFileStreamOptions, token?: CancellationToken): Promise<IFileStreamContent>;
    private doReadFileStream;
    private readFileStreamed;
    private readFileBuffered;
    private readFileUnbuffered;
    private validateReadFile;
    private validateReadFileLimits;
    canMove(source: URI, target: URI, overwrite?: boolean): Promise<Error | true>;
    canCopy(source: URI, target: URI, overwrite?: boolean): Promise<Error | true>;
    private doCanMoveCopy;
    move(source: URI, target: URI, overwrite?: boolean): Promise<IFileStatWithMetadata>;
    copy(source: URI, target: URI, overwrite?: boolean): Promise<IFileStatWithMetadata>;
    private doMoveCopy;
    private doCopyFile;
    private doCopyFolder;
    private doValidateMoveCopy;
    private getExtUri;
    private isPathCaseSensitive;
    createFolder(resource: URI): Promise<IFileStatWithMetadata>;
    private mkdirp;
    canDelete(resource: URI, options?: Partial<IFileDeleteOptions>): Promise<Error | true>;
    private doValidateDelete;
    del(resource: URI, options?: Partial<IFileDeleteOptions>): Promise<void>;
    cloneFile(source: URI, target: URI): Promise<void>;
    private readonly _onDidFilesChange;
    readonly onDidFilesChange: import("vs/base/common/event").Event<FileChangesEvent>;
    private readonly _onDidWatchError;
    readonly onDidWatchError: import("vs/base/common/event").Event<Error>;
    private readonly activeWatchers;
    watch(resource: URI, options?: IWatchOptions): IDisposable;
    private doWatch;
    dispose(): void;
    private readonly writeQueue;
    private doWriteBuffered;
    private doWriteStreamBufferedQueued;
    private doWriteReadableBufferedQueued;
    private doWriteBuffer;
    private doWriteUnbuffered;
    private doWriteUnbufferedQueued;
    private doPipeBuffered;
    private doPipeBufferedQueued;
    private doPipeUnbuffered;
    private doPipeUnbufferedQueued;
    private doPipeUnbufferedToBuffered;
    private doPipeUnbufferedToBufferedQueued;
    private doPipeBufferedToUnbuffered;
    protected throwIfFileSystemIsReadonly<T extends IFileSystemProvider>(provider: T, resource: URI): T;
    private throwIfFileIsReadonly;
    private resourceForError;
}
