import { Disposable } from 'vs/base/common/lifecycle';
import { ILogService } from 'vs/platform/log/common/log';
import { IPtyHostProcessReplayEvent, ISerializedCommandDetectionCapability } from 'vs/platform/terminal/common/capabilities/capabilities';
import { IProcessDataEvent, ITerminalChildProcess, ITerminalLaunchError, IProcessProperty, IProcessPropertyMap, ProcessPropertyType, IProcessReadyEvent } from 'vs/platform/terminal/common/terminal';
import { RemoteTerminalChannelClient } from 'vs/workbench/contrib/terminal/common/remoteTerminalChannel';
import { IRemoteAgentService } from 'vs/workbench/services/remote/common/remoteAgentService';
export declare class RemotePty extends Disposable implements ITerminalChildProcess {
    private _id;
    readonly shouldPersist: boolean;
    private readonly _remoteTerminalChannel;
    private readonly _remoteAgentService;
    private readonly _logService;
    private readonly _onProcessData;
    readonly onProcessData: import("vs/base/common/event").Event<string | IProcessDataEvent>;
    private readonly _onProcessReady;
    readonly onProcessReady: import("vs/base/common/event").Event<IProcessReadyEvent>;
    private readonly _onDidChangeProperty;
    readonly onDidChangeProperty: import("vs/base/common/event").Event<IProcessProperty<any>>;
    private readonly _onProcessExit;
    readonly onProcessExit: import("vs/base/common/event").Event<number | undefined>;
    private readonly _onRestoreCommands;
    readonly onRestoreCommands: import("vs/base/common/event").Event<ISerializedCommandDetectionCapability>;
    private _startBarrier;
    private _inReplay;
    private _properties;
    get id(): number;
    constructor(_id: number, shouldPersist: boolean, _remoteTerminalChannel: RemoteTerminalChannelClient, _remoteAgentService: IRemoteAgentService, _logService: ILogService);
    start(): Promise<ITerminalLaunchError | undefined>;
    detach(forcePersist?: boolean): Promise<void>;
    shutdown(immediate: boolean): void;
    input(data: string): void;
    resize(cols: number, rows: number): void;
    freePortKillProcess(port: string): Promise<{
        port: string;
        processId: string;
    }>;
    acknowledgeDataEvent(charCount: number): void;
    setUnicodeVersion(version: '6' | '11'): Promise<void>;
    getInitialCwd(): Promise<string>;
    getCwd(): Promise<string>;
    refreshProperty<T extends ProcessPropertyType>(type: T): Promise<IProcessPropertyMap[T]>;
    updateProperty<T extends ProcessPropertyType>(type: T, value: IProcessPropertyMap[T]): Promise<void>;
    handleData(e: string | IProcessDataEvent): void;
    handleExit(e: number | undefined): void;
    processBinary(e: string): Promise<void>;
    handleReady(e: IProcessReadyEvent): void;
    handleDidChangeProperty({ type, value }: IProcessProperty<any>): void;
    handleReplay(e: IPtyHostProcessReplayEvent): Promise<void>;
    handleOrphanQuestion(): void;
    getLatency(): Promise<number>;
}
