import 'vs/css!./media/extensionsViewlet';
import { IWorkbenchContribution } from 'vs/workbench/common/contributions';
import { Disposable } from 'vs/base/common/lifecycle';
import { Dimension } from 'vs/base/browser/dom';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IExtensionService } from 'vs/workbench/services/extensions/common/extensions';
import { IExtensionsWorkbenchService, IExtensionsViewPaneContainer } from '../common/extensions';
import { IExtensionManagementService } from 'vs/platform/extensionManagement/common/extensionManagement';
import { IWorkbenchExtensionEnablementService, IExtensionManagementServerService } from 'vs/workbench/services/extensionManagement/common/extensionManagement';
import { IProgressService } from 'vs/platform/progress/common/progress';
import { IEditorGroupsService } from 'vs/workbench/services/editor/common/editorGroupsService';
import { IActivityService } from 'vs/workbench/services/activity/common/activity';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IViewDescriptorService, IAddedViewDescriptorRef } from 'vs/workbench/common/views';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IWorkspaceContextService } from 'vs/platform/workspace/common/workspace';
import { IContextKeyService, RawContextKey } from 'vs/platform/contextkey/common/contextkey';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { ILogService } from 'vs/platform/log/common/log';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { IHostService } from 'vs/workbench/services/host/browser/host';
import { IWorkbenchLayoutService } from 'vs/workbench/services/layout/browser/layoutService';
import { ViewPaneContainer } from 'vs/workbench/browser/parts/views/viewPaneContainer';
import { ViewPane } from 'vs/workbench/browser/parts/views/viewPane';
import { ILabelService } from 'vs/platform/label/common/label';
import { IPreferencesService } from 'vs/workbench/services/preferences/common/preferences';
import { IWorkbenchEnvironmentService } from 'vs/workbench/services/environment/common/environmentService';
import { ICommandService } from 'vs/platform/commands/common/commands';
import { IPaneCompositePartService } from 'vs/workbench/services/panecomposite/browser/panecomposite';
export declare const DefaultViewsContext: RawContextKey<boolean>;
export declare const ExtensionsSortByContext: RawContextKey<string>;
export declare const SearchMarketplaceExtensionsContext: RawContextKey<boolean>;
export declare const SearchHasTextContext: RawContextKey<boolean>;
export declare const BuiltInExtensionsContext: RawContextKey<boolean>;
export declare const RecommendedExtensionsContext: RawContextKey<boolean>;
export declare class ExtensionsViewletViewsContribution implements IWorkbenchContribution {
    private readonly extensionManagementServerService;
    private readonly labelService;
    private readonly contextKeyService;
    private readonly container;
    constructor(extensionManagementServerService: IExtensionManagementServerService, labelService: ILabelService, viewDescriptorService: IViewDescriptorService, contextKeyService: IContextKeyService);
    private registerViews;
    private createDefaultExtensionsViewDescriptors;
    private createSearchExtensionsViewDescriptors;
    private createRecommendedExtensionsViewDescriptors;
    private createBuiltinExtensionsViewDescriptors;
    private createUnsupportedWorkspaceExtensionsViewDescriptors;
    private createOtherLocalFilteredExtensionsViewDescriptors;
}
export declare class ExtensionsViewPaneContainer extends ViewPaneContainer implements IExtensionsViewPaneContainer {
    private readonly progressService;
    private readonly editorGroupService;
    private readonly extensionsWorkbenchService;
    private readonly extensionManagementServerService;
    private readonly notificationService;
    private readonly paneCompositeService;
    private readonly contextKeyService;
    private readonly preferencesService;
    private readonly commandService;
    private defaultViewsContextKey;
    private sortByContextKey;
    private searchMarketplaceExtensionsContextKey;
    private searchHasTextContextKey;
    private sortByUpdateDateContextKey;
    private searchInstalledExtensionsContextKey;
    private searchRecentlyUpdatedExtensionsContextKey;
    private searchExtensionUpdatesContextKey;
    private searchOutdatedExtensionsContextKey;
    private searchEnabledExtensionsContextKey;
    private searchDisabledExtensionsContextKey;
    private hasInstalledExtensionsContextKey;
    private builtInExtensionsContextKey;
    private searchBuiltInExtensionsContextKey;
    private searchWorkspaceUnsupportedExtensionsContextKey;
    private searchDeprecatedExtensionsContextKey;
    private recommendedExtensionsContextKey;
    private searchDelayer;
    private root;
    private searchBox;
    private readonly searchViewletState;
    constructor(layoutService: IWorkbenchLayoutService, telemetryService: ITelemetryService, progressService: IProgressService, instantiationService: IInstantiationService, editorGroupService: IEditorGroupsService, extensionsWorkbenchService: IExtensionsWorkbenchService, extensionManagementServerService: IExtensionManagementServerService, notificationService: INotificationService, paneCompositeService: IPaneCompositePartService, themeService: IThemeService, configurationService: IConfigurationService, storageService: IStorageService, contextService: IWorkspaceContextService, contextKeyService: IContextKeyService, contextMenuService: IContextMenuService, extensionService: IExtensionService, viewDescriptorService: IViewDescriptorService, preferencesService: IPreferencesService, commandService: ICommandService);
    get searchValue(): string | undefined;
    create(parent: HTMLElement): void;
    focus(): void;
    layout(dimension: Dimension): void;
    getOptimalWidth(): number;
    search(value: string): void;
    refresh(): Promise<void>;
    private updateInstalledExtensionsContexts;
    private triggerSearch;
    private normalizedQuery;
    saveState(): void;
    private doSearch;
    protected onDidAddViewDescriptors(added: IAddedViewDescriptorRef[]): ViewPane[];
    private alertSearchResult;
    private count;
    private focusListView;
    private onViewletOpen;
    private progress;
    private onError;
    private isSupportedDragElement;
}
export declare class StatusUpdater extends Disposable implements IWorkbenchContribution {
    private readonly activityService;
    private readonly extensionsWorkbenchService;
    private readonly extensionEnablementService;
    private readonly badgeHandle;
    constructor(activityService: IActivityService, extensionsWorkbenchService: IExtensionsWorkbenchService, extensionEnablementService: IWorkbenchExtensionEnablementService);
    private onServiceChange;
}
export declare class MaliciousExtensionChecker implements IWorkbenchContribution {
    private readonly extensionsManagementService;
    private readonly hostService;
    private readonly logService;
    private readonly notificationService;
    private readonly environmentService;
    constructor(extensionsManagementService: IExtensionManagementService, hostService: IHostService, logService: ILogService, notificationService: INotificationService, environmentService: IWorkbenchEnvironmentService);
    private loopCheckForMaliciousExtensions;
    private checkForMaliciousExtensions;
}
