import 'vs/css!./media/typeHierarchy';
import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { IPosition } from 'vs/editor/common/core/position';
import { ITextModelService } from 'vs/editor/common/services/resolverService';
import * as peekView from 'vs/editor/contrib/peekView/browser/peekView';
import { IMenuService, MenuId } from 'vs/platform/actions/common/actions';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import * as typeHTree from 'vs/workbench/contrib/typeHierarchy/browser/typeHierarchyTree';
import { TypeHierarchyDirection, TypeHierarchyModel } from 'vs/workbench/contrib/typeHierarchy/common/typeHierarchy';
import { IEditorService } from 'vs/workbench/services/editor/common/editorService';
export declare class TypeHierarchyTreePeekWidget extends peekView.PeekViewWidget {
    private readonly _where;
    private _direction;
    private readonly _peekViewService;
    private readonly _editorService;
    private readonly _textModelService;
    private readonly _storageService;
    private readonly _menuService;
    private readonly _contextKeyService;
    private readonly _instantiationService;
    static readonly TitleMenu: MenuId;
    private _parent;
    private _message;
    private _splitView;
    private _tree;
    private _treeViewStates;
    private _editor;
    private _dim;
    private _layoutInfo;
    private readonly _previewDisposable;
    constructor(editor: ICodeEditor, _where: IPosition, _direction: TypeHierarchyDirection, themeService: IThemeService, _peekViewService: peekView.IPeekViewService, _editorService: IEditorService, _textModelService: ITextModelService, _storageService: IStorageService, _menuService: IMenuService, _contextKeyService: IContextKeyService, _instantiationService: IInstantiationService);
    dispose(): void;
    get direction(): TypeHierarchyDirection;
    private _applyTheme;
    protected _fillHead(container: HTMLElement): void;
    protected _fillBody(parent: HTMLElement): void;
    private _updatePreview;
    showLoading(): void;
    showMessage(message: string): void;
    showModel(model: TypeHierarchyModel): Promise<void>;
    getModel(): TypeHierarchyModel | undefined;
    getFocused(): typeHTree.Type | undefined;
    updateDirection(newDirection: TypeHierarchyDirection): Promise<void>;
    private _show;
    protected _onWidth(width: number): void;
    protected _doLayoutBody(height: number, width: number): void;
}
