import { Dimension } from 'vs/base/browser/dom';
import { IMouseWheelEvent } from 'vs/base/browser/mouseEvent';
import { Disposable } from 'vs/base/common/lifecycle';
import { URI } from 'vs/base/common/uri';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { ExtensionIdentifier } from 'vs/platform/extensions/common/extensions';
import { ILayoutService } from 'vs/platform/layout/browser/layoutService';
import { IOverlayWebview, IWebviewService, WebviewContentOptions, WebviewExtensionDescription, WebviewInitInfo, WebviewMessageReceivedEvent, WebviewOptions } from 'vs/workbench/contrib/webview/browser/webview';
/**
 * Webview that is absolutely positioned over another element and that can creates and destroys an underlying webview as needed.
 */
export declare class OverlayWebview extends Disposable implements IOverlayWebview {
    private readonly _layoutService;
    private readonly _webviewService;
    private readonly _baseContextKeyService;
    private _isFirstLoad;
    private readonly _firstLoadPendingMessages;
    private readonly _webview;
    private readonly _webviewEvents;
    private _html;
    private _initialScrollProgress;
    private _state;
    private _extension;
    private _contentOptions;
    private _options;
    private _owner;
    private readonly _scopedContextKeyService;
    private _findWidgetVisible;
    private _findWidgetEnabled;
    private _shouldShowFindWidgetOnRestore;
    readonly id: string;
    readonly providedViewType?: string;
    readonly origin: string;
    private _container;
    constructor(initInfo: WebviewInitInfo, _layoutService: ILayoutService, _webviewService: IWebviewService, _baseContextKeyService: IContextKeyService);
    get isFocused(): boolean;
    private _isDisposed;
    private readonly _onDidDispose;
    onDidDispose: import("vs/base/common/event").Event<void>;
    dispose(): void;
    get container(): HTMLElement;
    claim(owner: any, scopedContextKeyService: IContextKeyService | undefined): void;
    release(owner: any): void;
    layoutWebviewOverElement(element: HTMLElement, dimension?: Dimension, clippingContainer?: HTMLElement): void;
    private _show;
    get html(): string;
    set html(value: string);
    get initialScrollProgress(): number;
    set initialScrollProgress(value: number);
    get state(): string | undefined;
    set state(value: string | undefined);
    get extension(): WebviewExtensionDescription | undefined;
    set extension(value: WebviewExtensionDescription | undefined);
    get options(): WebviewOptions;
    set options(value: WebviewOptions);
    get contentOptions(): WebviewContentOptions;
    set contentOptions(value: WebviewContentOptions);
    set localResourcesRoot(resources: URI[]);
    private readonly _onDidFocus;
    readonly onDidFocus: import("vs/base/common/event").Event<void>;
    private readonly _onDidBlur;
    readonly onDidBlur: import("vs/base/common/event").Event<void>;
    private readonly _onDidClickLink;
    readonly onDidClickLink: import("vs/base/common/event").Event<string>;
    private readonly _onDidReload;
    readonly onDidReload: import("vs/base/common/event").Event<void>;
    private readonly _onDidScroll;
    readonly onDidScroll: import("vs/base/common/event").Event<{
        readonly scrollYPercentage: number;
    }>;
    private readonly _onDidUpdateState;
    readonly onDidUpdateState: import("vs/base/common/event").Event<string | undefined>;
    private readonly _onMessage;
    readonly onMessage: import("vs/base/common/event").Event<WebviewMessageReceivedEvent>;
    private readonly _onMissingCsp;
    readonly onMissingCsp: import("vs/base/common/event").Event<ExtensionIdentifier>;
    private readonly _onDidWheel;
    readonly onDidWheel: import("vs/base/common/event").Event<IMouseWheelEvent>;
    postMessage(message: any, transfer?: readonly ArrayBuffer[]): Promise<boolean>;
    focus(): void;
    reload(): void;
    selectAll(): void;
    copy(): void;
    paste(): void;
    cut(): void;
    undo(): void;
    redo(): void;
    showFind(animated?: boolean): void;
    hideFind(animated?: boolean): void;
    runFindAction(previous: boolean): void;
    private _withWebview;
    windowDidDragStart(): void;
    windowDidDragEnd(): void;
    setContextKeyService(contextKeyService: IContextKeyService): void;
}
