import 'vs/css!./media/activitybarpart';
import { Part } from 'vs/workbench/browser/part';
import { IBadge } from 'vs/workbench/services/activity/common/activity';
import { IWorkbenchLayoutService } from 'vs/workbench/services/layout/browser/layoutService';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IDisposable } from 'vs/base/common/lifecycle';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IExtensionService } from 'vs/workbench/services/extensions/common/extensions';
import { IViewDescriptorService } from 'vs/workbench/common/views';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IWorkbenchEnvironmentService } from 'vs/workbench/services/environment/common/environmentService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IPaneCompositePart, IPaneCompositeSelectorPart } from 'vs/workbench/browser/parts/paneCompositePart';
import { IUserDataProfileService } from 'vs/workbench/services/userDataProfile/common/userDataProfile';
import { IUserDataProfilesService } from 'vs/platform/userDataProfile/common/userDataProfile';
export declare class ActivitybarPart extends Part implements IPaneCompositeSelectorPart {
    private readonly paneCompositePart;
    private readonly instantiationService;
    private readonly storageService;
    private readonly extensionService;
    private readonly viewDescriptorService;
    private readonly contextKeyService;
    private readonly configurationService;
    private readonly environmentService;
    private readonly userDataProfileService;
    private readonly userDataProfilesService;
    readonly _serviceBrand: undefined;
    private static readonly PINNED_VIEW_CONTAINERS;
    private static readonly PLACEHOLDER_VIEW_CONTAINERS;
    private static readonly ACTION_HEIGHT;
    private static readonly ACCOUNTS_ACTION_INDEX;
    private static readonly GEAR_ICON;
    private static readonly ACCOUNTS_ICON;
    readonly minimumWidth: number;
    readonly maximumWidth: number;
    readonly minimumHeight: number;
    readonly maximumHeight: number;
    private content;
    private menuBar;
    private menuBarContainer;
    private compositeBar;
    private compositeBarContainer;
    private globalActivityAction;
    private globalActivityActionBar;
    private globalActivitiesContainer;
    private readonly globalActivity;
    private accountsActivityAction;
    private profilesActivityAction;
    private readonly accountsActivity;
    private readonly compositeActions;
    private readonly viewContainerDisposables;
    private readonly keyboardNavigationDisposables;
    private readonly location;
    private hasExtensionsRegistered;
    private readonly enabledViewContainersContextKeys;
    constructor(paneCompositePart: IPaneCompositePart, instantiationService: IInstantiationService, layoutService: IWorkbenchLayoutService, themeService: IThemeService, storageService: IStorageService, extensionService: IExtensionService, viewDescriptorService: IViewDescriptorService, contextKeyService: IContextKeyService, configurationService: IConfigurationService, environmentService: IWorkbenchEnvironmentService, userDataProfileService: IUserDataProfileService, userDataProfilesService: IUserDataProfilesService);
    private createCompositeBar;
    private getActivityHoverOptions;
    private getContextMenuActionsForComposite;
    private registerListeners;
    private onDidChangeViewContainers;
    private onDidChangeViewContainerLocation;
    private onDidChangeViewContainerVisibility;
    private onDidRegisterExtensions;
    private onDidViewContainerVisible;
    showActivity(viewContainerOrActionId: string, badge: IBadge, clazz?: string, priority?: number): IDisposable;
    private showGlobalActivity;
    private removeGlobalActivity;
    private updateGlobalActivity;
    private getCumulativeNumberBadge;
    private uninstallMenubar;
    private installMenubar;
    createContentArea(parent: HTMLElement): HTMLElement;
    private registerKeyboardNavigationListeners;
    private createGlobalActivityActionBar;
    private toggleAccountsActivity;
    private toggleProfilesActivityAction;
    private updateProfilesActivityAction;
    private createProfilesActivity;
    private getCompositeActions;
    private onDidRegisterViewContainers;
    private onDidDeregisterViewContainer;
    private updateActivity;
    private toActivity;
    private static toActivity;
    private showOrHideViewContainer;
    private shouldBeHidden;
    private addComposite;
    private hideComposite;
    private removeComposite;
    getPinnedPaneCompositeIds(): string[];
    getVisiblePaneCompositeIds(): string[];
    focus(): void;
    updateStyles(): void;
    private getActivitybarItemColors;
    private getProfileItemColors;
    layout(width: number, height: number): void;
    private getViewContainer;
    private getViewContainers;
    private onDidStorageValueChange;
    private saveCachedViewContainers;
    private _cachedViewContainers;
    private get cachedViewContainers();
    private storeCachedViewContainersState;
    private getPinnedViewContainers;
    private setPinnedViewContainers;
    private _pinnedViewContainersValue;
    private get pinnedViewContainersValue();
    private set pinnedViewContainersValue(value);
    private getStoredPinnedViewContainersValue;
    private setStoredPinnedViewContainersValue;
    private getPlaceholderViewContainers;
    private setPlaceholderViewContainers;
    private _placeholderViewContainersValue;
    private get placeholderViewContainersValue();
    private set placeholderViewContainersValue(value);
    private getStoredPlaceholderViewContainersValue;
    private setStoredPlaceholderViewContainersValue;
    private get accountsVisibilityPreference();
    private set accountsVisibilityPreference(value);
    private get profilesVisibilityPreference();
    private set profilesVisibilityPreference(value);
    toJSON(): object;
}
