import 'vs/css!./media/basepanelpart';
import 'vs/css!./media/panelpart';
import { IAction } from 'vs/base/common/actions';
import { Event } from 'vs/base/common/event';
import { CompositePart, ICompositeTitleLabel } from 'vs/workbench/browser/parts/compositePart';
import { IWorkbenchLayoutService, Parts } from 'vs/workbench/services/layout/browser/layoutService';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { IKeybindingService } from 'vs/platform/keybinding/common/keybinding';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { IActivityHoverOptions } from 'vs/workbench/browser/parts/compositeBarActions';
import { IBadge } from 'vs/workbench/services/activity/common/activity';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { Dimension } from 'vs/base/browser/dom';
import { IDisposable } from 'vs/base/common/lifecycle';
import { IContextKey, IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IExtensionService } from 'vs/workbench/services/extensions/common/extensions';
import { IViewDescriptorService, ViewContainerLocation } from 'vs/workbench/common/views';
import { IPaneComposite } from 'vs/workbench/common/panecomposite';
import { PaneComposite, PaneCompositeDescriptor } from 'vs/workbench/browser/panecomposite';
import { IPaneCompositePart, IPaneCompositeSelectorPart } from 'vs/workbench/browser/parts/paneCompositePart';
import { IPartOptions } from 'vs/workbench/browser/part';
import { ICommandService } from 'vs/platform/commands/common/commands';
interface IPanelPartOptions extends IPartOptions {
    hasTitle: true;
    borderWidth?: (() => number);
    useIcons?: boolean;
}
export declare abstract class BasePanelPart extends CompositePart<PaneComposite> implements IPaneCompositePart, IPaneCompositeSelectorPart {
    private readonly viewDescriptorService;
    protected readonly contextKeyService: IContextKeyService;
    private readonly extensionService;
    private readonly partId;
    protected readonly pinnedPanelsKey: string;
    protected readonly placeholdeViewContainersKey: string;
    private readonly backgroundColor;
    private readonly viewContainerLocation;
    private readonly activePanelContextKey;
    private panelFocusContextKey;
    private readonly panelOptions;
    private static readonly MIN_COMPOSITE_BAR_WIDTH;
    readonly _serviceBrand: undefined;
    readonly minimumWidth: number;
    readonly maximumWidth: number;
    readonly minimumHeight: number;
    readonly maximumHeight: number;
    readonly snap = true;
    get preferredHeight(): number | undefined;
    get preferredWidth(): number | undefined;
    get onDidPaneCompositeOpen(): Event<IPaneComposite>;
    readonly onDidPaneCompositeClose: Event<IPaneComposite>;
    private compositeBar;
    private readonly compositeActions;
    private globalToolBar;
    private globalActions;
    private readonly panelDisposables;
    private blockOpeningPanel;
    protected contentDimension: Dimension | undefined;
    private extensionsRegistered;
    private panelRegistry;
    private dndHandler;
    private readonly enabledViewContainersContextKeys;
    constructor(notificationService: INotificationService, storageService: IStorageService, telemetryService: ITelemetryService, contextMenuService: IContextMenuService, layoutService: IWorkbenchLayoutService, keybindingService: IKeybindingService, instantiationService: IInstantiationService, themeService: IThemeService, viewDescriptorService: IViewDescriptorService, contextKeyService: IContextKeyService, extensionService: IExtensionService, partId: Parts.PANEL_PART | Parts.AUXILIARYBAR_PART, activePanelSettingsKey: string, pinnedPanelsKey: string, placeholdeViewContainersKey: string, panelRegistryId: string, backgroundColor: string, viewContainerLocation: ViewContainerLocation, activePanelContextKey: IContextKey<string>, panelFocusContextKey: IContextKey<boolean>, panelOptions: IPanelPartOptions);
    protected abstract getActivityHoverOptions(): IActivityHoverOptions;
    protected abstract fillExtraContextMenuActions(actions: IAction[]): void;
    private getContextMenuActionsForComposite;
    private onDidRegisterPanels;
    private onDidDeregisterPanel;
    private updateActivity;
    private toActivity;
    private static toActivity;
    private showOrHideViewContainer;
    private shouldBeHidden;
    private registerListeners;
    private onDidRegisterExtensions;
    private hideComposite;
    private onPanelOpen;
    private onPanelClose;
    create(parent: HTMLElement): void;
    private createEmptyPanelMessage;
    createTitleArea(parent: HTMLElement): HTMLElement;
    updateStyles(): void;
    doOpenPanel(id: string, focus?: boolean): PaneComposite | undefined;
    openPaneComposite(id?: string, focus?: boolean): Promise<PaneComposite | undefined>;
    showActivity(panelId: string, badge: IBadge, clazz?: string): IDisposable;
    getPaneComposite(panelId: string): PaneCompositeDescriptor | undefined;
    getPaneComposites(): PaneCompositeDescriptor[];
    getPinnedPaneCompositeIds(): string[];
    getVisiblePaneCompositeIds(): string[];
    getActivePaneComposite(): IPaneComposite | undefined;
    getLastActivePaneCompositeId(): string;
    hideActivePaneComposite(): void;
    protected createTitleLabel(parent: HTMLElement): ICompositeTitleLabel;
    onTitleAreaUpdate(compositeId: string): void;
    layout(width: number, height: number, top: number, left: number): void;
    private layoutCompositeBar;
    private emptyPanelMessageElement;
    private layoutEmptyMessage;
    private getViewContainer;
    private updateGlobalToolbarActions;
    private getCompositeActions;
    protected removeComposite(compositeId: string): boolean;
    protected getToolbarWidth(): number;
    private onDidStorageValueChange;
    private saveCachedPanels;
    private getCachedPanels;
    private _cachedPanelsValue;
    private get cachedPanelsValue();
    private set cachedPanelsValue(value);
    private getStoredCachedPanelsValue;
    private setStoredCachedViewletsValue;
    private getPlaceholderViewContainers;
    private setPlaceholderViewContainers;
    private _placeholderViewContainersValue;
    private get placeholderViewContainersValue();
    private set placeholderViewContainersValue(value);
    private getStoredPlaceholderViewContainersValue;
    private setStoredPlaceholderViewContainersValue;
}
export declare class PanelPart extends BasePanelPart {
    private commandService;
    static readonly activePanelSettingsKey = "workbench.panelpart.activepanelid";
    static readonly pinnedPanelsKey = "workbench.panel.pinnedPanels";
    static readonly placeholdeViewContainersKey = "workbench.panel.placeholderPanels";
    constructor(notificationService: INotificationService, storageService: IStorageService, telemetryService: ITelemetryService, contextMenuService: IContextMenuService, layoutService: IWorkbenchLayoutService, keybindingService: IKeybindingService, instantiationService: IInstantiationService, themeService: IThemeService, viewDescriptorService: IViewDescriptorService, contextKeyService: IContextKeyService, extensionService: IExtensionService, commandService: ICommandService);
    updateStyles(): void;
    protected getActivityHoverOptions(): IActivityHoverOptions;
    protected fillExtraContextMenuActions(actions: IAction[]): void;
    layout(width: number, height: number, top: number, left: number): void;
    toJSON(): object;
}
export {};
