import 'vs/css!./media/issueReporter';
import 'vs/base/browser/ui/codicons/codiconStyles';
import { Disposable } from 'vs/base/common/lifecycle';
import { IssueReporterWindowConfiguration } from 'vs/platform/issue/common/issue';
export declare function startup(configuration: IssueReporterWindowConfiguration): void;
export declare class IssueReporter extends Disposable {
    private readonly configuration;
    private nativeHostService;
    private readonly issueReporterModel;
    private numberOfSearchResultsDisplayed;
    private receivedSystemInfo;
    private receivedPerformanceInfo;
    private shouldQueueSearch;
    private hasBeenSubmitted;
    private delayedSubmit;
    private readonly previewButton;
    constructor(configuration: IssueReporterWindowConfiguration);
    render(): void;
    setInitialFocus(): void;
    private applyStyles;
    private handleExtensionData;
    private setEventHandlers;
    private updatePreviewButtonState;
    private isPreviewEnabled;
    private getExtensionRepositoryUrl;
    private getExtensionBugsUrl;
    private searchVSCodeIssues;
    private searchIssues;
    private searchExtensionIssues;
    private searchMarketplaceIssues;
    private clearSearchResults;
    private searchGitHub;
    private searchDuplicates;
    private displaySearchResults;
    private setUpTypes;
    private makeOption;
    private setSourceOptions;
    private renderBlocks;
    private validateInput;
    private validateInputs;
    private submitToGitHub;
    private createIssue;
    private writeToClipboard;
    private getIssueUrl;
    private parseGitHubUrl;
    private getExtensionGitHubUrl;
    private getIssueUrlWithTitle;
    private updateSystemInfo;
    private updateExtensionSelector;
    private validateSelectedExtension;
    private setExtensionValidationMessage;
    private updateProcessInfo;
    private updateWorkspaceInfo;
    private updateExtensionTable;
    private updateRestrictedMode;
    private updateUnsupportedMode;
    private updateExperimentsInfo;
    private getExtensionTableHtml;
    private openLink;
    private getElementById;
    private addEventListener;
}
