import 'vs/css!./media/sidebarpart';
import 'vs/workbench/browser/parts/sidebar/sidebarActions';
import { CompositePart } from 'vs/workbench/browser/parts/compositePart';
import { PaneCompositeDescriptor, PaneComposite } from 'vs/workbench/browser/panecomposite';
import { IWorkbenchLayoutService } from 'vs/workbench/services/layout/browser/layoutService';
import { IStorageService } from 'vs/platform/storage/common/storage';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { ITelemetryService } from 'vs/platform/telemetry/common/telemetry';
import { IKeybindingService } from 'vs/platform/keybinding/common/keybinding';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { Event } from 'vs/base/common/event';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { AnchorAlignment } from 'vs/base/browser/ui/contextview/contextview';
import { IExtensionService } from 'vs/workbench/services/extensions/common/extensions';
import { LayoutPriority } from 'vs/base/browser/ui/grid/grid';
import { IViewDescriptorService } from 'vs/workbench/common/views';
import { IPaneComposite } from 'vs/workbench/common/panecomposite';
import { IPaneCompositePart } from 'vs/workbench/browser/parts/paneCompositePart';
export declare class SidebarPart extends CompositePart<PaneComposite> implements IPaneCompositePart {
    private readonly viewDescriptorService;
    private readonly contextKeyService;
    private readonly extensionService;
    readonly _serviceBrand: undefined;
    static readonly activeViewletSettingsKey = "workbench.sidebar.activeviewletid";
    readonly minimumWidth: number;
    readonly maximumWidth: number;
    readonly minimumHeight: number;
    readonly maximumHeight: number;
    readonly priority: LayoutPriority;
    readonly snap = true;
    get preferredWidth(): number | undefined;
    get onDidPaneCompositeRegister(): Event<PaneCompositeDescriptor>;
    private _onDidViewletDeregister;
    readonly onDidPaneCompositeDeregister: Event<PaneCompositeDescriptor>;
    get onDidPaneCompositeOpen(): Event<IPaneComposite>;
    get onDidPaneCompositeClose(): Event<IPaneComposite>;
    private readonly viewletRegistry;
    private readonly sideBarFocusContextKey;
    private readonly activeViewletContextKey;
    private blockOpeningViewlet;
    constructor(notificationService: INotificationService, storageService: IStorageService, telemetryService: ITelemetryService, contextMenuService: IContextMenuService, layoutService: IWorkbenchLayoutService, keybindingService: IKeybindingService, instantiationService: IInstantiationService, themeService: IThemeService, viewDescriptorService: IViewDescriptorService, contextKeyService: IContextKeyService, extensionService: IExtensionService);
    private registerListeners;
    create(parent: HTMLElement): void;
    createTitleArea(parent: HTMLElement): HTMLElement;
    updateStyles(): void;
    layout(width: number, height: number, top: number, left: number): void;
    getActivePaneComposite(): IPaneComposite | undefined;
    getLastActivePaneCompositeId(): string;
    hideActivePaneComposite(): void;
    openPaneComposite(id: string | undefined, focus?: boolean): Promise<IPaneComposite | undefined>;
    getPaneComposites(): PaneCompositeDescriptor[];
    getPaneComposite(id: string): PaneCompositeDescriptor;
    private doOpenViewlet;
    protected getTitleAreaDropDownAnchorAlignment(): AnchorAlignment;
    private onTitleAreaContextMenu;
    toJSON(): object;
}
