declare const x01 = "string";
declare const x02 = "'";
declare const x03 = "\n'\t";
declare const x04 = "this is///         ^^^^^^^^^ stringa multiline string";
declare const x05 = "string";
declare const x06 = "string";
declare const x07: number;
declare const x08 = "howdy";
declare const x09 = "'\"`";
declare const x10 = "$[]";
declare const x11: string;
declare const x12: string;
declare const x13: RegExp;
declare const x14: RegExp;
declare const x15: number;
declare const x16: boolean;
declare const x17: string;
declare const x18: number;
declare const x19: string;
