import { IKeyboardEvent } from 'vs/base/browser/keyboardEvent';
import { IMouseEvent } from 'vs/base/browser/mouseEvent';
import { Toggle } from 'vs/base/browser/ui/toggle/toggle';
import { IContextViewProvider } from 'vs/base/browser/ui/contextview/contextview';
import { CaseSensitiveToggle, RegexToggle, WholeWordsToggle } from 'vs/base/browser/ui/findinput/findInputToggles';
import { HistoryInputBox, IInputBoxStyles, IInputValidator, IMessage as InputBoxMessage } from 'vs/base/browser/ui/inputbox/inputBox';
import { Widget } from 'vs/base/browser/ui/widget';
import { Color } from 'vs/base/common/color';
import { Event } from 'vs/base/common/event';
import 'vs/css!./findInput';
export interface IFindInputOptions extends IFindInputStyles {
    readonly placeholder?: string;
    readonly width?: number;
    readonly validation?: IInputValidator;
    readonly label: string;
    readonly flexibleHeight?: boolean;
    readonly flexibleWidth?: boolean;
    readonly flexibleMaxHeight?: number;
    readonly showCommonFindToggles?: boolean;
    readonly appendCaseSensitiveLabel?: string;
    readonly appendWholeWordsLabel?: string;
    readonly appendRegexLabel?: string;
    readonly history?: string[];
    readonly additionalToggles?: Toggle[];
    readonly showHistoryHint?: () => boolean;
}
export interface IFindInputStyles extends IInputBoxStyles {
    inputActiveOptionBorder?: Color;
    inputActiveOptionForeground?: Color;
    inputActiveOptionBackground?: Color;
}
export declare class FindInput extends Widget {
    static readonly OPTION_CHANGE: string;
    private placeholder;
    private validation?;
    private label;
    private readonly showCommonFindToggles;
    private fixFocusOnOptionClickEnabled;
    private imeSessionInProgress;
    private additionalTogglesDisposables;
    protected inputActiveOptionBorder?: Color;
    protected inputActiveOptionForeground?: Color;
    protected inputActiveOptionBackground?: Color;
    protected inputBackground?: Color;
    protected inputForeground?: Color;
    protected inputBorder?: Color;
    protected inputValidationInfoBorder?: Color;
    protected inputValidationInfoBackground?: Color;
    protected inputValidationInfoForeground?: Color;
    protected inputValidationWarningBorder?: Color;
    protected inputValidationWarningBackground?: Color;
    protected inputValidationWarningForeground?: Color;
    protected inputValidationErrorBorder?: Color;
    protected inputValidationErrorBackground?: Color;
    protected inputValidationErrorForeground?: Color;
    protected readonly controls: HTMLDivElement;
    protected readonly regex?: RegexToggle;
    protected readonly wholeWords?: WholeWordsToggle;
    protected readonly caseSensitive?: CaseSensitiveToggle;
    protected additionalToggles: Toggle[];
    readonly domNode: HTMLElement;
    readonly inputBox: HistoryInputBox;
    private readonly _onDidOptionChange;
    readonly onDidOptionChange: Event<boolean>;
    private readonly _onKeyDown;
    readonly onKeyDown: Event<IKeyboardEvent>;
    private readonly _onMouseDown;
    readonly onMouseDown: Event<IMouseEvent>;
    private readonly _onInput;
    readonly onInput: Event<void>;
    private readonly _onKeyUp;
    readonly onKeyUp: Event<IKeyboardEvent>;
    private _onCaseSensitiveKeyDown;
    readonly onCaseSensitiveKeyDown: Event<IKeyboardEvent>;
    private _onRegexKeyDown;
    readonly onRegexKeyDown: Event<IKeyboardEvent>;
    constructor(parent: HTMLElement | null, contextViewProvider: IContextViewProvider | undefined, options: IFindInputOptions);
    get isImeSessionInProgress(): boolean;
    get onDidChange(): Event<string>;
    enable(): void;
    disable(): void;
    setFocusInputOnOptionClick(value: boolean): void;
    setEnabled(enabled: boolean): void;
    setAdditionalToggles(toggles: Toggle[] | undefined): void;
    clear(): void;
    getValue(): string;
    setValue(value: string): void;
    onSearchSubmit(): void;
    style(styles: IFindInputStyles): void;
    protected applyStyles(): void;
    select(): void;
    focus(): void;
    getCaseSensitive(): boolean;
    setCaseSensitive(value: boolean): void;
    getWholeWords(): boolean;
    setWholeWords(value: boolean): void;
    getRegex(): boolean;
    setRegex(value: boolean): void;
    focusOnCaseSensitive(): void;
    focusOnRegex(): void;
    private _lastHighlightFindOptions;
    highlightFindOptions(): void;
    validate(): void;
    showMessage(message: InputBoxMessage): void;
    clearMessage(): void;
    private clearValidation;
}
