import { Emitter, Event } from 'vs/base/common/event';
import { Disposable } from 'vs/base/common/lifecycle';
import 'vs/css!./media/diffEditor';
import { IEditorConstructionOptions } from 'vs/editor/browser/config/editorConfiguration';
import * as editorBrowser from 'vs/editor/browser/editorBrowser';
import { ICodeEditorService } from 'vs/editor/browser/services/codeEditorService';
import { CodeEditorWidget, ICodeEditorWidgetOptions } from 'vs/editor/browser/widget/codeEditorWidget';
import { IDiffEditorOptions } from 'vs/editor/common/config/editorOptions';
import { IDimension } from 'vs/editor/common/core/dimension';
import { IPosition, Position } from 'vs/editor/common/core/position';
import { IRange, Range } from 'vs/editor/common/core/range';
import { ISelection, Selection } from 'vs/editor/common/core/selection';
import { IChange, IDiffComputationResult, ILineChange } from 'vs/editor/common/diff/smartLinesDiffComputer';
import * as editorCommon from 'vs/editor/common/editorCommon';
import { IModelDecorationsChangeAccessor, IModelDeltaDecoration } from 'vs/editor/common/model';
import { IClipboardService } from 'vs/platform/clipboard/common/clipboardService';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IContextMenuService } from 'vs/platform/contextview/browser/contextView';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { INotificationService } from 'vs/platform/notification/common/notification';
import { IEditorProgressService } from 'vs/platform/progress/common/progress';
import { IThemeService } from 'vs/platform/theme/common/themeService';
export interface IDiffCodeEditorWidgetOptions {
    originalEditor?: ICodeEditorWidgetOptions;
    modifiedEditor?: ICodeEditorWidgetOptions;
}
export declare class DiffEditorWidget extends Disposable implements editorBrowser.IDiffEditor {
    private readonly _editorProgressService;
    private static readonly ONE_OVERVIEW_WIDTH;
    static readonly ENTIRE_DIFF_OVERVIEW_WIDTH = 30;
    private static readonly UPDATE_DIFF_DECORATIONS_DELAY;
    private readonly _onDidDispose;
    readonly onDidDispose: Event<void>;
    protected readonly _onDidChangeModel: Emitter<void>;
    readonly onDidChangeModel: Event<void>;
    private readonly _onDidUpdateDiff;
    readonly onDidUpdateDiff: Event<void>;
    private readonly _onDidContentSizeChange;
    readonly onDidContentSizeChange: Event<editorCommon.IContentSizeChangedEvent>;
    private readonly _id;
    private _state;
    private _updatingDiffProgress;
    private readonly _domElement;
    protected readonly _containerDomElement: HTMLElement;
    private readonly _overviewDomElement;
    private readonly _overviewViewportDomElement;
    private readonly _elementSizeObserver;
    private readonly _originalEditor;
    private readonly _originalDomNode;
    private readonly _originalEditorState;
    private _originalOverviewRuler;
    private readonly _modifiedEditor;
    private readonly _modifiedDomNode;
    private readonly _modifiedEditorState;
    private _modifiedOverviewRuler;
    private _currentlyChangingViewZones;
    private _beginUpdateDecorationsTimeout;
    private _diffComputationToken;
    private _diffComputationResult;
    private _isVisible;
    private _isHandlingScrollEvent;
    private _options;
    private _strategy;
    private readonly _updateDecorationsRunner;
    private readonly _documentDiffProvider;
    private readonly _contextKeyService;
    private readonly _instantiationService;
    private readonly _codeEditorService;
    private readonly _themeService;
    private readonly _notificationService;
    private readonly _reviewPane;
    constructor(domElement: HTMLElement, options: Readonly<editorBrowser.IDiffEditorConstructionOptions>, codeEditorWidgetOptions: IDiffCodeEditorWidgetOptions, clipboardService: IClipboardService, contextKeyService: IContextKeyService, instantiationService: IInstantiationService, codeEditorService: ICodeEditorService, themeService: IThemeService, notificationService: INotificationService, contextMenuService: IContextMenuService, _editorProgressService: IEditorProgressService);
    get ignoreTrimWhitespace(): boolean;
    get maxComputationTime(): number;
    get renderSideBySide(): boolean;
    getContentHeight(): number;
    getViewWidth(): number;
    private _setState;
    hasWidgetFocus(): boolean;
    diffReviewNext(): void;
    diffReviewPrev(): void;
    private static _getClassName;
    private _disposeOverviewRulers;
    private _createOverviewRulers;
    private _createLeftHandSideEditor;
    private _createRightHandSideEditor;
    /**
     * Reverts a change in the modified editor.
     */
    revertChange(change: IChange): void;
    protected _createInnerEditor(instantiationService: IInstantiationService, container: HTMLElement, options: Readonly<IEditorConstructionOptions>, editorWidgetOptions: ICodeEditorWidgetOptions): CodeEditorWidget;
    dispose(): void;
    getId(): string;
    getEditorType(): string;
    getLineChanges(): ILineChange[] | null;
    getDiffComputationResult(): IDiffComputationResult | null;
    getOriginalEditor(): editorBrowser.ICodeEditor;
    getModifiedEditor(): editorBrowser.ICodeEditor;
    updateOptions(_newOptions: Readonly<IDiffEditorOptions>): void;
    getModel(): editorCommon.IDiffEditorModel;
    setModel(model: editorCommon.IDiffEditorModel | null): void;
    getContainerDomNode(): HTMLElement;
    getVisibleColumnFromPosition(position: IPosition): number;
    getStatusbarColumn(position: IPosition): number;
    getPosition(): Position | null;
    setPosition(position: IPosition, source?: string): void;
    revealLine(lineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLineInCenter(lineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLineInCenterIfOutsideViewport(lineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLineNearTop(lineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealPosition(position: IPosition, scrollType?: editorCommon.ScrollType): void;
    revealPositionInCenter(position: IPosition, scrollType?: editorCommon.ScrollType): void;
    revealPositionInCenterIfOutsideViewport(position: IPosition, scrollType?: editorCommon.ScrollType): void;
    revealPositionNearTop(position: IPosition, scrollType?: editorCommon.ScrollType): void;
    getSelection(): Selection | null;
    getSelections(): Selection[] | null;
    setSelection(range: IRange, source?: string): void;
    setSelection(editorRange: Range, source?: string): void;
    setSelection(selection: ISelection, source?: string): void;
    setSelection(editorSelection: Selection, source?: string): void;
    setSelections(ranges: readonly ISelection[], source?: string): void;
    revealLines(startLineNumber: number, endLineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLinesInCenter(startLineNumber: number, endLineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLinesInCenterIfOutsideViewport(startLineNumber: number, endLineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealLinesNearTop(startLineNumber: number, endLineNumber: number, scrollType?: editorCommon.ScrollType): void;
    revealRange(range: IRange, scrollType?: editorCommon.ScrollType, revealVerticalInCenter?: boolean, revealHorizontal?: boolean): void;
    revealRangeInCenter(range: IRange, scrollType?: editorCommon.ScrollType): void;
    revealRangeInCenterIfOutsideViewport(range: IRange, scrollType?: editorCommon.ScrollType): void;
    revealRangeNearTop(range: IRange, scrollType?: editorCommon.ScrollType): void;
    revealRangeNearTopIfOutsideViewport(range: IRange, scrollType?: editorCommon.ScrollType): void;
    revealRangeAtTop(range: IRange, scrollType?: editorCommon.ScrollType): void;
    getSupportedActions(): editorCommon.IEditorAction[];
    saveViewState(): editorCommon.IDiffEditorViewState;
    restoreViewState(s: editorCommon.IDiffEditorViewState): void;
    layout(dimension?: IDimension): void;
    focus(): void;
    hasTextFocus(): boolean;
    onVisible(): void;
    onHide(): void;
    trigger(source: string | null | undefined, handlerId: string, payload: any): void;
    createDecorationsCollection(decorations?: IModelDeltaDecoration[]): editorCommon.IEditorDecorationsCollection;
    changeDecorations(callback: (changeAccessor: IModelDecorationsChangeAccessor) => any): any;
    private _onDidContainerSizeChanged;
    private _getReviewHeight;
    private _layoutOverviewRulers;
    private _onViewZonesChanged;
    private _beginUpdateDecorationsSoon;
    private _lastOriginalWarning;
    private _lastModifiedWarning;
    private static _equals;
    private _beginUpdateDecorations;
    private _cleanViewZonesAndDecorations;
    private _updateDecorations;
    private _adjustOptionsForSubEditor;
    private _adjustOptionsForLeftHandSide;
    private _adjustOptionsForRightHandSide;
    doLayout(): void;
    private _doLayout;
    private _layoutOverviewViewport;
    private _computeOverviewViewport;
    private _createDataSource;
    private _setStrategy;
    private _getLineChangeAtOrBeforeLineNumber;
    private _getEquivalentLineForOriginalLineNumber;
    private _getEquivalentLineForModifiedLineNumber;
    getDiffLineInformationForOriginal(lineNumber: number): editorBrowser.IDiffLineInformation | null;
    getDiffLineInformationForModified(lineNumber: number): editorBrowser.IDiffLineInformation | null;
}
