import { Disposable } from 'vs/base/common/lifecycle';
import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { IEditorOptions } from 'vs/editor/common/config/editorOptions';
import { ILanguageService } from 'vs/editor/common/languages/language';
import { IAccessibilityService } from 'vs/platform/accessibility/common/accessibility';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IInstantiationService } from 'vs/platform/instantiation/common/instantiation';
import { IKeybindingService } from 'vs/platform/keybinding/common/keybinding';
import { IActiveNotebookEditorDelegate, ICellViewModel } from 'vs/workbench/contrib/notebook/browser/notebookBrowser';
import { MarkdownCellRenderTemplate } from 'vs/workbench/contrib/notebook/browser/view/notebookRenderingCommon';
import { MarkupCellViewModel } from 'vs/workbench/contrib/notebook/browser/viewModel/markupCellViewModel';
import { INotebookCellStatusBarService } from 'vs/workbench/contrib/notebook/common/notebookCellStatusBarService';
export declare class MarkupCell extends Disposable {
    private readonly notebookEditor;
    private readonly viewCell;
    private readonly templateData;
    private readonly renderedEditors;
    private readonly accessibilityService;
    private readonly contextKeyService;
    readonly notebookCellStatusBarService: INotebookCellStatusBarService;
    private readonly instantiationService;
    private readonly languageService;
    private configurationService;
    private keybindingService;
    private editor;
    private markdownAccessibilityContainer;
    private editorPart;
    private readonly localDisposables;
    private readonly focusSwitchDisposable;
    private readonly editorDisposables;
    private foldingState;
    private cellEditorOptions;
    private editorOptions;
    constructor(notebookEditor: IActiveNotebookEditorDelegate, viewCell: MarkupCellViewModel, templateData: MarkdownCellRenderTemplate, renderedEditors: Map<ICellViewModel, ICodeEditor | undefined>, accessibilityService: IAccessibilityService, contextKeyService: IContextKeyService, notebookCellStatusBarService: INotebookCellStatusBarService, instantiationService: IInstantiationService, languageService: ILanguageService, configurationService: IConfigurationService, keybindingService: IKeybindingService);
    layoutCellParts(): void;
    private constructDOM;
    private registerListeners;
    private updateCollapsedState;
    private updateForHover;
    private updateForFocusModeChange;
    private applyDecorations;
    dispose(): void;
    private updateFoldingIconShowClass;
    private viewUpdate;
    private viewUpdateCollapsed;
    private getRichText;
    private viewUpdateEditing;
    private viewUpdatePreview;
    private focusEditorIfNeeded;
    private layoutEditor;
    private onCellEditorWidthChange;
    relayoutCell(): void;
    updateEditorOptions(newValue: IEditorOptions): void;
    private layoutFoldingIndicator;
    private bindEditorListeners;
}
