import * as dom from 'vs/base/browser/dom';
import { FindInput } from 'vs/base/browser/ui/findinput/findInput';
import { ReplaceInput } from 'vs/base/browser/ui/findinput/replaceInput';
import { InputBox } from 'vs/base/browser/ui/inputbox/inputBox';
import { Widget } from 'vs/base/browser/ui/widget';
import { Event } from 'vs/base/common/event';
import { IClipboardService } from 'vs/platform/clipboard/common/clipboardService';
import { IConfigurationService } from 'vs/platform/configuration/common/configuration';
import { IContextKeyService } from 'vs/platform/contextkey/common/contextkey';
import { IContextViewService } from 'vs/platform/contextview/browser/contextView';
import { IKeybindingService } from 'vs/platform/keybinding/common/keybinding';
import { IThemeService } from 'vs/platform/theme/common/themeService';
import { IAccessibilityService } from 'vs/platform/accessibility/common/accessibility';
/** Specified in searchview.css */
export declare const SingleLineInputHeight = 24;
export interface ISearchWidgetOptions {
    value?: string;
    replaceValue?: string;
    isRegex?: boolean;
    isCaseSensitive?: boolean;
    isWholeWords?: boolean;
    searchHistory?: string[];
    replaceHistory?: string[];
    preserveCase?: boolean;
    _hideReplaceToggle?: boolean;
    showContextToggle?: boolean;
}
export declare class SearchWidget extends Widget {
    private readonly contextViewService;
    private readonly themeService;
    private readonly contextKeyService;
    private readonly keybindingService;
    private readonly clipboardServce;
    private readonly configurationService;
    private readonly accessibilityService;
    private static readonly INPUT_MAX_HEIGHT;
    private static readonly REPLACE_ALL_DISABLED_LABEL;
    private static readonly REPLACE_ALL_ENABLED_LABEL;
    domNode: HTMLElement;
    searchInput: FindInput;
    searchInputFocusTracker: dom.IFocusTracker;
    private searchInputBoxFocused;
    private replaceContainer;
    replaceInput: ReplaceInput;
    replaceInputFocusTracker: dom.IFocusTracker;
    private replaceInputBoxFocused;
    private toggleReplaceButton;
    private replaceAllAction;
    private replaceActive;
    private replaceActionBar;
    private _replaceHistoryDelayer;
    private ignoreGlobalFindBufferOnNextFocus;
    private previousGlobalFindBufferValue;
    private _onSearchSubmit;
    readonly onSearchSubmit: Event<{
        triggeredOnType: boolean;
        delay: number;
    }>;
    private _onSearchCancel;
    readonly onSearchCancel: Event<{
        focus: boolean;
    }>;
    private _onReplaceToggled;
    readonly onReplaceToggled: Event<void>;
    private _onReplaceStateChange;
    readonly onReplaceStateChange: Event<boolean>;
    private _onPreserveCaseChange;
    readonly onPreserveCaseChange: Event<boolean>;
    private _onReplaceValueChanged;
    readonly onReplaceValueChanged: Event<void>;
    private _onReplaceAll;
    readonly onReplaceAll: Event<void>;
    private _onBlur;
    readonly onBlur: Event<void>;
    private _onDidHeightChange;
    readonly onDidHeightChange: Event<void>;
    private readonly _onDidToggleContext;
    readonly onDidToggleContext: Event<void>;
    private showContextToggle;
    contextLinesInput: InputBox;
    constructor(container: HTMLElement, options: ISearchWidgetOptions, contextViewService: IContextViewService, themeService: IThemeService, contextKeyService: IContextKeyService, keybindingService: IKeybindingService, clipboardServce: IClipboardService, configurationService: IConfigurationService, accessibilityService: IAccessibilityService);
    focus(select?: boolean, focusReplace?: boolean, suppressGlobalSearchBuffer?: boolean): void;
    setWidth(width: number): void;
    clear(): void;
    isReplaceShown(): boolean;
    isReplaceActive(): boolean;
    getReplaceValue(): string;
    toggleReplace(show?: boolean): void;
    getSearchHistory(): string[];
    getReplaceHistory(): string[];
    clearHistory(): void;
    showNextSearchTerm(): void;
    showPreviousSearchTerm(): void;
    showNextReplaceTerm(): void;
    showPreviousReplaceTerm(): void;
    searchInputHasFocus(): boolean;
    replaceInputHasFocus(): boolean;
    focusReplaceAllAction(): void;
    focusRegexAction(): void;
    private render;
    private updateAccessibilitySupport;
    private renderToggleReplaceButton;
    private renderSearchInput;
    private onContextLinesChanged;
    setContextLines(lines: number): void;
    private renderReplaceInput;
    triggerReplaceAll(): Promise<any>;
    private onToggleReplaceButton;
    setValue(value: string): void;
    setReplaceAllActionState(enabled: boolean): void;
    private updateReplaceActiveState;
    private validateSearchInput;
    private onSearchInputChanged;
    private onSearchInputKeyDown;
    private onCaseSensitiveKeyDown;
    private onRegexKeyDown;
    private onPreserveCaseKeyDown;
    private onReplaceInputKeyDown;
    private onReplaceActionbarKeyDown;
    private submitSearch;
    getContextLines(): number;
    modifyContextLines(increase: boolean): void;
    toggleContextLines(): void;
    dispose(): void;
    private get searchConfiguration();
}
export declare function registerContributions(): void;
