import { KeyCode } from 'vs/base/common/keyCodes';
import { Disposable } from 'vs/base/common/lifecycle';
import 'vs/css!./dnd';
import { ICodeEditor } from 'vs/editor/browser/editorBrowser';
import { Position } from 'vs/editor/common/core/position';
import { IEditorContribution } from 'vs/editor/common/editorCommon';
export declare class DragAndDropController extends Disposable implements IEditorContribution {
    static readonly ID = "editor.contrib.dragAndDrop";
    private readonly _editor;
    private _dragSelection;
    private readonly _dndDecorationIds;
    private _mouseDown;
    private _modifierPressed;
    static readonly TRIGGER_KEY_VALUE: KeyCode;
    static get(editor: ICodeEditor): DragAndDropController | null;
    constructor(editor: ICodeEditor);
    private onEditorBlur;
    private onEditorKeyDown;
    private onEditorKeyUp;
    private _onEditorMouseDown;
    private _onEditorMouseUp;
    private _onEditorMouseDrag;
    private _onEditorMouseDropCanceled;
    private _onEditorMouseDrop;
    private static readonly _DECORATION_OPTIONS;
    showAt(position: Position): void;
    private _removeDecoration;
    private _hitContent;
    private _hitMargin;
    dispose(): void;
}
